'use strict';
const express=require('express');
const crypto=require('crypto');
const {waitUntil}=require('@vercel/functions');
const {answer}=require('../services/zorgaxAssistantService');
const {COMIC_URL,wantsComicImage,selectComicAsset,comicContext}=require('../services/messengerComicService');
const router=express.Router();
const MAX_HISTORY_MESSAGES=10,HISTORY_TTL_MS=30*60*1000,MAX_CONVERSATIONS=500;
const conversationMemory=new Map();
function configured(){return Boolean(process.env.META_WEBHOOK_VERIFY_TOKEN&&process.env.META_APP_SECRET&&process.env.META_PAGE_ACCESS_TOKEN)}
function safeEqual(a,b){const l=Buffer.from(String(a||'')),r=Buffer.from(String(b||''));return l.length===r.length&&crypto.timingSafeEqual(l,r)}
function validSignature(req){const secret=process.env.META_APP_SECRET,sig=req.get('x-hub-signature-256');if(!secret||!sig||!sig.startsWith('sha256=')||!Buffer.isBuffer(req.rawBody))return false;return safeEqual(sig,`sha256=${crypto.createHmac('sha256',secret).update(req.rawBody).digest('hex')}`)}
function cleanupMemory(now=Date.now()){for(const[k,v]of conversationMemory)if(!v?.updatedAt||now-v.updatedAt>HISTORY_TTL_MS)conversationMemory.delete(k);while(conversationMemory.size>MAX_CONVERSATIONS)conversationMemory.delete(conversationMemory.keys().next().value)}
function conversationKey(id){return crypto.createHash('sha256').update(String(id||'')).digest('hex')}
function getHistory(id){cleanupMemory();return(conversationMemory.get(conversationKey(id))?.history||[]).slice(-MAX_HISTORY_MESSAGES)}
function rememberTurn(id,userText,assistantText){cleanupMemory();const key=conversationKey(id),current=conversationMemory.get(key)?.history||[];conversationMemory.delete(key);conversationMemory.set(key,{history:[...current,{role:'user',content:String(userText||'').slice(0,1200)},{role:'assistant',content:String(assistantText||'').slice(0,1900)}].slice(-MAX_HISTORY_MESSAGES),updatedAt:Date.now()})}
function cleanMessengerText(v){return String(v||'').replace(/```[\s\S]*?```/g,b=>b.replace(/```(?:\w+)?\n?/g,'').replace(/```/g,'')).replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'$1: $2').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/__([^_]+)__/g,'$1').replace(/(^|\s)[*_]([^*_\n]+)[*_](?=\s|$)/g,'$1$2').replace(/^#{1,6}\s+/gm,'').replace(/^\s*[-*+]\s+/gm,'• ').replace(/`([^`]+)`/g,'$1').replace(/\n{3,}/g,'\n\n').trim()}
function messengerPrompt(message,media=''){return `MESSENGER CHANNEL RULES:\n- Reply in the same language as the user's latest meaningful message.\n- Keep replies concise and conversational: normally 2-6 short lines.\n- No Markdown formatting. Plain text, short lines and emoji are fine.\n- Give one immediate next step first.\n- Live destinations: Marketplace/Seller https://www.myzubster.com/marketplace ; Metaverse https://www.myzubster.com/metaverse ; LIFE Pilot https://www.myzubster.com/life-pilot ; Community/login https://www.myzubster.com/social-login ; Comic Universe ${COMIC_URL}.\n- Buyer access is free. Configured default Seller plan is EUR 9.90/month; live configuration can change. Never invent fees, commissions, discounts, refunds or commercial terms.\n- For Seller price questions state EUR 9.90/month as configured default and ask the user to verify the live Marketplace price.\n- Guide onboarding one confirmed step at a time.\n- COMIC SAFETY: fiction, concept art and historical-reference visuals are narrative media, not proof of real events. Never elevate an attached comic image into evidence.\n${media}\nUSER MESSAGE:\n${String(message||'').trim()}`}
async function askZorgax(message,senderId,asset){const result=await answer({message:messengerPrompt(message,asset?comicContext(asset):''),useWeb:false,history:getHistory(senderId),limit:1});const raw=String(result?.answer||result?.text||result?.response||result?.message||'').trim(),text=cleanMessengerText(raw).slice(0,1900);if(!text)throw new Error('Zorgax ha restituito una risposta vuota');rememberTurn(senderId,message,text);return text}
function graphEndpoint(){const token=process.env.META_PAGE_ACCESS_TOKEN;if(!token)throw new Error('META_PAGE_ACCESS_TOKEN non configurato');return `https://graph.facebook.com/${process.env.META_GRAPH_API_VERSION||'v26.0'}/me/messages?access_token=${encodeURIComponent(token)}`}
async function sendPayload(recipientId,message){const response=await fetch(graphEndpoint(),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipient:{id:recipientId},messaging_type:'RESPONSE',message})});if(!response.ok){const detail=await response.text().catch(()=> '');throw new Error(`Meta Send API ${response.status}${detail?`: ${detail.slice(0,300)}`:''}`)}}
async function sendMessage(id,text){return sendPayload(id,{text})}
async function sendImage(id,url){return sendPayload(id,{attachment:{type:'image',payload:{url,is_reusable:true}}})}
async function handleMessageEvent(event){try{const asset=wantsComicImage(event.text)?selectComicAsset(event.text):null;const reply=await askZorgax(event.text,event.senderId,asset);if(asset){try{await sendImage(event.senderId,asset.url)}catch(e){console.error('[meta-messenger]',`comic_image_send_failed: ${e.message}`)}}await sendMessage(event.senderId,reply);console.info('[meta-messenger]',JSON.stringify({event:'message_handled',mode:'zorgax',history:'warm-instance',comicImage:Boolean(asset)}))}catch(error){console.error('[meta-messenger]',error.message);try{await sendMessage(event.senderId,'Zorgax è temporaneamente non disponibile. Riprova tra poco.')}catch(e){console.error('[meta-messenger]',`fallback_send_failed: ${e.message}`)}}}
router.get('/status',(_req,res)=>res.json({ok:true,service:'meta-messenger-community-bridge',configured:configured(),zorgaxAI:true,conversationMemory:'ephemeral-warm-instance',comicMedia:true,comicUniverse:COMIC_URL,webhook:'https://www.myzubster.com/api/meta/messenger/webhook'}));
router.get('/webhook',(req,res)=>{const mode=req.query['hub.mode'],token=req.query['hub.verify_token'];if(mode==='subscribe'&&process.env.META_WEBHOOK_VERIFY_TOKEN&&safeEqual(token,process.env.META_WEBHOOK_VERIFY_TOKEN))return res.status(200).send(String(req.query['hub.challenge']||''));return res.sendStatus(403)});
router.post('/webhook',async(req,res)=>{if(!validSignature(req))return res.sendStatus(401);const events=[];for(const entry of req.body?.entry||[])for(const event of entry.messaging||[]){if(event.message?.is_echo)continue;const senderId=event.sender?.id,text=String(event.message?.text||'').trim();if(senderId&&text)events.push({senderId,text})}if(events.length)waitUntil(Promise.allSettled(events.map(handleMessageEvent)));return res.sendStatus(200)});
module.exports=router;module.exports._test={safeEqual,validSignature,configured,handleMessageEvent,cleanMessengerText,messengerPrompt,getHistory,rememberTurn,wantsComicImage,selectComicAsset};
