'use strict';

const express = require('express');
const jwt = require('jsonwebtoken');
const dashboard = require('../services/settlementDashboardService');
const PaymentDashboardTransaction = require('../models/PaymentDashboardTransaction');
const { stripeFundingInputsProvider } = require('../services/paymentDashboardStripeProvider');
const { createControlledCheckout, verifyControlledCheckout } = require('../services/paymentDashboardCheckoutService');
const router = express.Router();
const FILTER_KEYS = ['q','status','program','account','from','to'];
const DEFAULT_PAYMENT_ADMIN_GITHUB_LOGINS = ['danielioni-creator'];
const DEFAULT_MYZ_PER_EUR = 10;
function readFilter(query={}){const filter={};for(const key of FILTER_KEYS){if(query[key]!==undefined&&query[key]!=='')filter[key]=query[key];}return filter;}
function auth(req,res,next){const h=req.header('Authorization')||'';const token=h.startsWith('Bearer ')?h.slice(7):null;if(!token)return res.status(401).json({error:'No token provided'});const secret=process.env.JWT_SECRET;if(!secret)return res.status(503).json({error:'Authentication is not configured'});try{req.user=jwt.verify(token,secret);return next();}catch(_){return res.status(401).json({error:'Invalid token'});}}
function githubLogin(user){const value=user?.github||user?.login||user?.username||'';return typeof value==='string'?value.trim().toLowerCase():'';}
function configuredPaymentAdmins(){const configured=String(process.env.PAYMENT_DASHBOARD_ADMIN_GITHUB_LOGINS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);return new Set([...DEFAULT_PAYMENT_ADMIN_GITHUB_LOGINS,...configured]);}
function isAdminUser(user){return user?.role==='admin'||configuredPaymentAdmins().has(githubLogin(user));}
function admin(req,res,next){if(!isAdminUser(req.user))return res.status(403).json({error:'Admin required'});return next();}
function resolveAccountId(user){if(!user)return null;if(typeof user.accountId==='string'&&user.accountId)return user.accountId;const login=user.github||user.username||user.login;if(typeof login==='string'&&login)return `contributor:github:${login}`;if(user.userId)return `contributor:${user.userId}`;return null;}
function scopeItems(items,accountId){return accountId?items.filter(i=>i.accountId===accountId):items;}
function buildFor(req){const isAdmin=isAdminUser(req.user);const requested=typeof req.query.account==='string'&&req.query.account?req.query.account:null;return dashboard.buildDashboard({filter:readFilter(req.query),accountId:isAdmin?requested:resolveAccountId(req.user)});}
function myzRate(){const rate=Number(process.env.MYZ_PER_EUR||DEFAULT_MYZ_PER_EUR);return Number.isFinite(rate)&&rate>0?rate:DEFAULT_MYZ_PER_EUR;}
function accountingConversion(result){if(!result?.paid||String(result.currency||'').toLowerCase()!=='eur')return null;const rate=myzRate();const eur=Number(result.amountTotal||0)/100;return {sourceAsset:'EUR',targetAsset:'MYZ',rateMyzPerEur:rate,amountMyz:Math.round(eur*rate*1e6)/1e6,state:'ACCOUNTING_RECORDED',recordedAt:new Date()};}
function paymentAccountId(result){const actor=typeof result?.actor==='string'?result.actor.trim():'';return actor?`contributor:github:${actor}`:null;}
async function persistVerifiedPayment(result){if(!result?.paid)return null;const conversion=accountingConversion(result);return PaymentDashboardTransaction.findOneAndUpdate({checkoutSessionId:result.sessionId},{ $set:{provider:'STRIPE',paymentIntentId:result.paymentIntentId||undefined,actor:result.actor||undefined,requestHash:result.requestHash||undefined,amountCents:Number(result.amountTotal||0),currency:String(result.currency||'').toUpperCase(),paymentStatus:String(result.paymentStatus||'paid'),checkoutStatus:result.status||undefined,livemode:result.livemode===true,customerEmail:result.customerEmail||undefined,stripeCreatedAt:result.createdAt?new Date(result.createdAt):undefined,verifiedAt:new Date(),...(conversion?{conversion}:{} )}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});}
async function ensureMyzCredit(result,transaction){if(!result?.paid||!transaction?.conversion||transaction.conversion.state!=='ACCOUNTING_RECORDED')return transaction;const accountId=paymentAccountId(result);const amountMyz=Number(transaction.conversion.amountMyz||0);if(!accountId||!Number.isFinite(amountMyz)||amountMyz<=0)return transaction;const sourceReference=`stripe:${result.sessionId}`;const updated=await PaymentDashboardTransaction.findOneAndUpdate({checkoutSessionId:result.sessionId,'myzCredit.state':{$ne:'RECORDED'}},{ $set:{myzCredit:{accountId,amountMyz,entryType:'ADJUSTMENT_CREDIT',state:'RECORDED',sourceReference,recordedAt:new Date()}}},{new:true,runValidators:true});return updated||PaymentDashboardTransaction.findOne({checkoutSessionId:result.sessionId});}
async function runtimeMyzCredits(accountId=null){const query={'myzCredit.state':'RECORDED'};if(accountId)query['myzCredit.accountId']=accountId;const rows=await PaymentDashboardTransaction.find(query,{'myzCredit':1,'checkoutSessionId':1}).lean();const amount=Math.round(rows.reduce((sum,row)=>sum+Number(row.myzCredit?.amountMyz||0),0)*1e6)/1e6;return {amount,count:rows.length,items:rows.map(row=>({checkoutSessionId:row.checkoutSessionId,...row.myzCredit}))};}
async function augmentMyzBalance(payload,accountId=null){const credits=await runtimeMyzCredits(accountId);const myz=payload?.balances?.myz;if(!myz)return payload;const canonical=Number(myz.amount||0);myz.canonicalAmount=canonical;myz.runtimeCredits=credits.amount;myz.runtimeCreditCount=credits.count;myz.amount=Math.round((canonical+credits.amount)*1e6)/1e6;myz.basis='canonical RECORDED ledger entries plus idempotent RECORDED Stripe-backed MYZ credits';myz.source='myz/ledger.json + MongoDB PaymentDashboardTransaction.myzCredit';return payload;}
router.get('/summary',auth,async(req,res)=>{try{const p=buildFor(req);const requested=isAdminUser(req.user)&&typeof req.query.account==='string'&&req.query.account?req.query.account:null;const accountId=requested||(!isAdminUser(req.user)?resolveAccountId(req.user):null);await augmentMyzBalance(p,accountId);if(!isAdminUser(req.user)){const a=resolveAccountId(req.user);p.layers.bounty_rewards.items=scopeItems(p.layers.bounty_rewards.items,a);p.layers.xmr_payouts.items=scopeItems(p.layers.xmr_payouts.items,a);}return res.json(p);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/meta',auth,(req,res)=>{try{const p=buildFor(req);return res.json({generatedAt:p.generatedAt,live:p.live,policy:p.policy,sources:p.sources,warnings:p.warnings,integrity:p.integrity,configured:{fundingInputs:p.layers.funding_inputs.configured,conversion:p.layers.conversion.configured,escrow:p.layers.escrow.configured},accountingConversion:{enabled:true,sourceAsset:'EUR',targetAsset:'MYZ',rateMyzPerEur:myzRate(),redeemableForFiat:false,autoCreditMyz:true}});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/balances',auth,async(req,res)=>{try{const p=buildFor(req);const requested=isAdminUser(req.user)&&typeof req.query.account==='string'&&req.query.account?req.query.account:null;const accountId=requested||(!isAdminUser(req.user)?resolveAccountId(req.user):null);await augmentMyzBalance(p,accountId);return res.json(p.balances);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/funding-inputs/stripe',auth,admin,async(_req,res)=>{try{return res.json(await stripeFundingInputsProvider());}catch(e){return res.status(502).json({configured:true,provider:'stripe-readonly',items:[],error:e.message});}});
router.get('/checkout/stripe/verify',auth,admin,async(req,res)=>{try{const result=await verifyControlledCheckout(req.query.session_id);let transaction=await persistVerifiedPayment(result);transaction=await ensureMyzCredit(result,transaction);return res.json({...result,recorded:Boolean(transaction),transactionId:transaction?String(transaction._id):null,conversion:transaction?.conversion||null,myzCredit:transaction?.myzCredit||null});}catch(e){return res.status(400).json({error:e.message});}});
router.get('/transactions',auth,admin,async(req,res)=>{try{const limit=Math.min(Math.max(Number(req.query.limit||25),1),100);const items=await PaymentDashboardTransaction.find({}).sort({verifiedAt:-1}).limit(limit).lean();return res.json({items,count:items.length,accountingConversion:{rateMyzPerEur:myzRate(),redeemableForFiat:false,autoCreditMyz:true}});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/myz-credits',auth,admin,async(req,res)=>{try{const account=typeof req.query.account==='string'&&req.query.account?req.query.account:null;const credits=await runtimeMyzCredits(account);return res.json({configured:true,idempotentBy:'checkoutSessionId',entryType:'ADJUSTMENT_CREDIT',state:'RECORDED',...credits});}catch(e){return res.status(500).json({error:e.message});}});
/* Controlled write: creates a hosted Checkout Session only. No refunds, transfers or payouts. */
router.post('/checkout/stripe',auth,admin,express.json({limit:'8kb'}),async(req,res)=>{try{const result=await createControlledCheckout({input:req.body,actor:req.user,idempotencyKey:req.header('Idempotency-Key')});return res.status(201).json(result);}catch(e){return res.status(400).json({error:e.message});}});
router.get('/funding-inputs',auth,admin,(req,res)=>{try{return res.json(buildFor(req).layers.funding_inputs);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/available-balance',auth,admin,(req,res)=>{try{return res.json(buildFor(req).layers.available_balance);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/conversion',auth,admin,async(req,res)=>{try{const items=await PaymentDashboardTransaction.find({'conversion.state':'ACCOUNTING_RECORDED'}).sort({'conversion.recordedAt':-1}).limit(Math.min(Math.max(Number(req.query.limit||25),1),100)).lean();return res.json({configured:true,mode:'accounting-only',sourceAsset:'EUR',targetAsset:'MYZ',rateMyzPerEur:myzRate(),redeemableForFiat:false,autoCreditMyz:true,items:items.map(i=>({checkoutSessionId:i.checkoutSessionId,amountEur:Number(i.amountCents||0)/100,amountMyz:i.conversion?.amountMyz||0,rateMyzPerEur:i.conversion?.rateMyzPerEur||myzRate(),state:i.conversion?.state||'ACCOUNTING_RECORDED',myzCredit:i.myzCredit||null,recordedAt:i.conversion?.recordedAt||i.verifiedAt}))});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/escrow',auth,(req,res)=>{try{const l=buildFor(req).layers.escrow;return res.json(l.configured?l:{...l,items:[]});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/bounties',auth,(req,res)=>{try{const l=buildFor(req).layers.bounty_rewards;if(!isAdminUser(req.user))l.items=scopeItems(l.items,resolveAccountId(req.user));return res.json(l);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/payouts',auth,(req,res)=>{try{const l=buildFor(req).layers.xmr_payouts;if(!isAdminUser(req.user))l.items=scopeItems(l.items,resolveAccountId(req.user));return res.json(l);}catch(e){return res.status(500).json({error:e.message});}});
module.exports=router;
module.exports._internal={auth,admin,isAdminUser,githubLogin,configuredPaymentAdmins,readFilter,resolveAccountId,scopeItems,myzRate,accountingConversion,paymentAccountId,persistVerifiedPayment,ensureMyzCredit,runtimeMyzCredits,augmentMyzBalance};
