'use strict';

const express = require('express');
const jwt = require('jsonwebtoken');
const dashboard = require('../services/settlementDashboardService');
const PaymentDashboardTransaction = require('../models/PaymentDashboardTransaction');
const MyzUtilityRedemption = require('../models/MyzUtilityRedemption');
const utilityCatalog = require('../../myz/utility-catalog.json');
const { stripeFundingInputsProvider } = require('../services/paymentDashboardStripeProvider');
const { createControlledCheckout, verifyControlledCheckout } = require('../services/paymentDashboardCheckoutService');
const myzLedgerApiService = require('../services/myzLedgerApiService');
const router = express.Router();
const FILTER_KEYS = ['q','status','program','account','from','to'];
const DEFAULT_PAYMENT_ADMIN_GITHUB_LOGINS = ['danielioni-creator'];
function readFilter(query={}){const filter={};for(const key of FILTER_KEYS){if(query[key]!==undefined&&query[key]!=='')filter[key]=query[key];}return filter;}
function auth(req,res,next){const h=req.header('Authorization')||'';const token=h.startsWith('Bearer ')?h.slice(7):null;if(!token)return res.status(401).json({error:'No token provided'});const secret=process.env.JWT_SECRET;if(!secret)return res.status(503).json({error:'Authentication is not configured'});try{req.user=jwt.verify(token,secret);return next();}catch(_){return res.status(401).json({error:'Invalid token'});}}
function githubLogin(user){const value=user?.github||user?.login||user?.username||'';return typeof value==='string'?value.trim().toLowerCase():'';}
function configuredPaymentAdmins(){const configured=String(process.env.PAYMENT_DASHBOARD_ADMIN_GITHUB_LOGINS||'').split(',').map(v=>v.trim().toLowerCase()).filter(Boolean);return new Set([...DEFAULT_PAYMENT_ADMIN_GITHUB_LOGINS,...configured]);}
function isAdminUser(user){return user?.role==='admin'||configuredPaymentAdmins().has(githubLogin(user));}
function admin(req,res,next){if(!isAdminUser(req.user))return res.status(403).json({error:'Admin required'});return next();}
function resolveAccountId(user){if(!user)return null;if(typeof user.accountId==='string'&&user.accountId)return user.accountId;const login=user.github||user.username||user.login;if(typeof login==='string'&&login)return `contributor:github:${login}`;if(user.userId)return `contributor:${user.userId}`;return null;}
function scopeItems(items,accountId){return accountId?items.filter(i=>i.accountId===accountId):items;}
function buildFor(req){const isAdmin=isAdminUser(req.user);const requested=typeof req.query.account==='string'&&req.query.account?req.query.account:null;return dashboard.buildDashboard({filter:readFilter(req.query),accountId:isAdmin?requested:resolveAccountId(req.user)});}
function myzRate(){return null;}
function accountingConversion(){return null;}
function paymentAccountId(result){const actor=typeof result?.actor==='string'?result.actor.trim():'';return actor?`contributor:github:${actor}`:null;}
async function persistVerifiedPayment(result){if(!result?.paid)return null;const conversion=accountingConversion(result);return PaymentDashboardTransaction.findOneAndUpdate({checkoutSessionId:result.sessionId},{ $set:{provider:'STRIPE',paymentIntentId:result.paymentIntentId||undefined,actor:result.actor||undefined,requestHash:result.requestHash||undefined,amountCents:Number(result.amountTotal||0),currency:String(result.currency||'').toUpperCase(),paymentStatus:String(result.paymentStatus||'paid'),checkoutStatus:result.status||undefined,livemode:result.livemode===true,customerEmail:result.customerEmail||undefined,stripeCreatedAt:result.createdAt?new Date(result.createdAt):undefined,verifiedAt:new Date(),...(conversion?{conversion}:{} )}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});}
async function ensureMyzCredit(_result,transaction){return transaction;}
async function runtimeMyzCredits(accountId=null){const query={'myzCredit.state':'RECORDED'};if(accountId)query['myzCredit.accountId']=accountId;const rows=await PaymentDashboardTransaction.find(query,{'myzCredit':1,'checkoutSessionId':1}).lean();const amount=Math.round(rows.reduce((sum,row)=>sum+Number(row.myzCredit?.amountMyz||0),0)*1e6)/1e6;return {amount,count:rows.length,items:rows.map(row=>({checkoutSessionId:row.checkoutSessionId,...row.myzCredit}))};}
async function runtimeMyzDebits(accountId=null){const query={state:'RECORDED'};if(accountId)query.accountId=accountId;const rows=await MyzUtilityRedemption.find(query).sort({recordedAt:-1}).lean();const amount=Math.round(rows.reduce((sum,row)=>sum+Number(row.amountMyz||0),0)*1e6)/1e6;return {amount,count:rows.length,items:rows};}
async function augmentMyzBalance(payload,_accountId=null){const myz=payload?.balances?.myz;if(!myz)return payload;const canonical=Number(myz.amount||0);myz.canonicalAmount=canonical;myz.amount=canonical;myz.basis='canonical RECORDED ledger entries only';myz.source='myz/ledger.json';myz.legacyMongoCreditsExcluded=true;myz.legacyMongoDebitsExcluded=true;return payload;}
async function spendableMyz(accountId){return Number(myzLedgerApiService.getBalance(accountId).balanceMyz||0);}
function findOffer(offerId){return (utilityCatalog.offers||[]).find(o=>o.id===offerId&&o.status==='PILOT')||null;}
router.get('/summary',auth,async(req,res)=>{try{const p=buildFor(req);const requested=isAdminUser(req.user)&&typeof req.query.account==='string'&&req.query.account?req.query.account:null;const accountId=requested||(!isAdminUser(req.user)?resolveAccountId(req.user):null);await augmentMyzBalance(p,accountId);if(!isAdminUser(req.user)){const a=resolveAccountId(req.user);p.layers.bounty_rewards.items=scopeItems(p.layers.bounty_rewards.items,a);p.layers.xmr_payouts.items=scopeItems(p.layers.xmr_payouts.items,a);}return res.json(p);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/meta',auth,(req,res)=>{try{const p=buildFor(req);return res.json({generatedAt:p.generatedAt,live:p.live,policy:p.policy,sources:p.sources,warnings:p.warnings,integrity:p.integrity,configured:{fundingInputs:p.layers.funding_inputs.configured,conversion:p.layers.conversion.configured,escrow:p.layers.escrow.configured},accountingConversion:{enabled:false,sourceAsset:'EUR',targetAsset:'MYZ',rateMyzPerEur:null,redeemableForFiat:false,autoCreditMyz:false,reason:'No EUR-to-MYZ conversion policy is active'},utility:{enabled:true,catalogSchema:utilityCatalog.schema}});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/balances',auth,async(req,res)=>{try{const p=buildFor(req);const requested=isAdminUser(req.user)&&typeof req.query.account==='string'&&req.query.account?req.query.account:null;const accountId=requested||(!isAdminUser(req.user)?resolveAccountId(req.user):null);await augmentMyzBalance(p,accountId);return res.json(p.balances);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/utility-catalog',auth,(req,res)=>res.json(utilityCatalog));
router.get('/myz-redemptions',auth,async(req,res)=>{try{const requested=isAdminUser(req.user)&&typeof req.query.account==='string'&&req.query.account?req.query.account:null;const accountId=requested||resolveAccountId(req.user);const debits=await runtimeMyzDebits(accountId);return res.json({accountId,...debits});}catch(e){return res.status(500).json({error:e.message});}});
router.post('/myz-redemptions/:id/fulfill',auth,admin,express.json({limit:'4kb'}),async(req,res)=>{try{const reference=String(req.body?.fulfillmentReference||'').trim();if(reference.length>320)return res.status(400).json({error:'Fulfillment reference too long'});const existing=await MyzUtilityRedemption.findById(req.params.id);if(!existing)return res.status(404).json({error:'Redemption not found'});if(existing.fulfillmentState==='FULFILLED')return res.json({fulfilled:true,idempotentReplay:true,redemption:existing});if(existing.fulfillmentState==='CANCELLED')return res.status(409).json({error:'Cancelled redemption cannot be fulfilled'});existing.fulfillmentState='FULFILLED';existing.fulfilledAt=new Date();existing.fulfillmentReference=reference||`fulfilled:${existing.offerId}:${existing._id}`;await existing.save();return res.json({fulfilled:true,idempotentReplay:false,redemption:existing});}catch(e){return res.status(400).json({error:e.message});}});
router.post('/myz-spend',auth,express.json({limit:'4kb'}),async(req,res)=>{try{const accountId=resolveAccountId(req.user);if(!accountId)return res.status(400).json({error:'Account identity unavailable'});const offer=findOffer(String(req.body?.offerId||''));if(!offer)return res.status(400).json({error:'Unknown or unavailable MYZ utility offer'});const key=String(req.header('Idempotency-Key')||'').trim();if(!key||key.length>180)return res.status(400).json({error:'Valid Idempotency-Key required'});const existing=await MyzUtilityRedemption.findOne({idempotencyKey:key}).lean();if(existing){if(existing.accountId!==accountId||existing.offerId!==offer.id)return res.status(409).json({error:'Idempotency-Key already used for another redemption'});return res.json({recorded:true,idempotentReplay:true,redemption:existing,balanceMyz:await spendableMyz(accountId)});}
 const price=Number(offer.price_myz);if(!Number.isFinite(price)||price<=0)return res.status(500).json({error:'Invalid catalog price'});
 let debit;try{debit=myzLedgerApiService.appendDebit({account_id:accountId,amount_myz:`-${price}`,idempotency_key:`payment-dashboard-utility:${key}`,reference:{type:'MYZ_UTILITY_REDEMPTION',offer_id:offer.id},note:`Internal MYZ utility purchase: ${offer.name}`});}catch(e){if(e?.code==='INSUFFICIENT_MYZ_BALANCE')return res.status(409).json({error:'Insufficient MYZ balance',balanceMyz:await spendableMyz(accountId),requiredMyz:price});if(e?.code==='MYZ_LEDGER_IDEMPOTENCY_CONFLICT')return res.status(409).json({error:e.message,code:e.code});throw e;}
 let redemption;try{redemption=await MyzUtilityRedemption.create({idempotencyKey:key,accountId,offerId:offer.id,offerName:offer.name,amountMyz:price,entryType:'ADJUSTMENT_DEBIT',state:'RECORDED',fulfillmentState:'PENDING',sourceReference:`utility:${offer.id}:${key}`,ledgerEntryId:debit.entry.entry_id,recordedAt:new Date()});}catch(e){if(e&&e.code===11000){const replay=await MyzUtilityRedemption.findOne({idempotencyKey:key}).lean();return res.json({recorded:true,idempotentReplay:true,redemption:replay,balanceMyz:await spendableMyz(accountId)});}throw e;}
 return res.status(debit.duplicate?200:201).json({recorded:true,idempotentReplay:debit.duplicate,redemption,balanceMyz:await spendableMyz(accountId),ledgerEntryId:debit.entry.entry_id});
 }catch(e){return res.status(500).json({error:e.message});}});
router.get('/funding-inputs/stripe',auth,admin,async(_req,res)=>{try{return res.json(await stripeFundingInputsProvider());}catch(e){return res.status(502).json({configured:true,provider:'stripe-readonly',items:[],error:e.message});}});
router.get('/checkout/stripe/verify',auth,admin,async(req,res)=>{try{const result=await verifyControlledCheckout(req.query.session_id);let transaction=await persistVerifiedPayment(result);transaction=await ensureMyzCredit(result,transaction);return res.json({...result,recorded:Boolean(transaction),transactionId:transaction?String(transaction._id):null,conversion:null,myzCredit:null,myzAutoCredit:false});}catch(e){return res.status(400).json({error:e.message});}});
router.get('/transactions',auth,admin,async(req,res)=>{try{const limit=Math.min(Math.max(Number(req.query.limit||25),1),100);const items=await PaymentDashboardTransaction.find({}).sort({verifiedAt:-1}).limit(limit).lean();return res.json({items,count:items.length,accountingConversion:{enabled:false,rateMyzPerEur:null,redeemableForFiat:false,autoCreditMyz:false}});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/myz-credits',auth,admin,async(req,res)=>{try{const account=typeof req.query.account==='string'&&req.query.account?req.query.account:null;const credits=await runtimeMyzCredits(account);return res.json({configured:false,legacy:true,spendable:false,autoCreditMyz:false,reason:'Historical MongoDB MYZ credits are excluded from canonical balances pending an explicit migration policy',...credits});}catch(e){return res.status(500).json({error:e.message});}});
/* Controlled write: creates a hosted Checkout Session only. No refunds, transfers or payouts. */
router.post('/checkout/stripe',auth,admin,express.json({limit:'8kb'}),async(req,res)=>{try{const result=await createControlledCheckout({input:req.body,actor:req.user,idempotencyKey:req.header('Idempotency-Key')});return res.status(201).json(result);}catch(e){return res.status(400).json({error:e.message});}});
router.get('/funding-inputs',auth,admin,(req,res)=>{try{return res.json(buildFor(req).layers.funding_inputs);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/available-balance',auth,admin,(req,res)=>{try{return res.json(buildFor(req).layers.available_balance);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/conversion',auth,admin,async(req,res)=>{try{const items=await PaymentDashboardTransaction.find({'conversion.state':'ACCOUNTING_RECORDED'}).sort({'conversion.recordedAt':-1}).limit(Math.min(Math.max(Number(req.query.limit||25),1),100)).lean();return res.json({configured:false,enabled:false,mode:'disabled',sourceAsset:'EUR',targetAsset:'MYZ',rateMyzPerEur:null,redeemableForFiat:false,autoCreditMyz:false,reason:'No EUR-to-MYZ conversion policy is active',legacyItems:items.map(i=>({checkoutSessionId:i.checkoutSessionId,amountEur:Number(i.amountCents||0)/100,amountMyz:i.conversion?.amountMyz||0,legacyRateMyzPerEur:i.conversion?.rateMyzPerEur||null,state:'LEGACY_ACCOUNTING_RECORDED_NON_SPENDABLE',recordedAt:i.conversion?.recordedAt||i.verifiedAt}))});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/escrow',auth,(req,res)=>{try{const l=buildFor(req).layers.escrow;return res.json(l.configured?l:{...l,items:[]});}catch(e){return res.status(500).json({error:e.message});}});
router.get('/bounties',auth,(req,res)=>{try{const l=buildFor(req).layers.bounty_rewards;if(!isAdminUser(req.user))l.items=scopeItems(l.items,resolveAccountId(req.user));return res.json(l);}catch(e){return res.status(500).json({error:e.message});}});
router.get('/payouts',auth,(req,res)=>{try{const l=buildFor(req).layers.xmr_payouts;if(!isAdminUser(req.user))l.items=scopeItems(l.items,resolveAccountId(req.user));return res.json(l);}catch(e){return res.status(500).json({error:e.message});}});
module.exports=router;
module.exports._internal={auth,admin,isAdminUser,githubLogin,configuredPaymentAdmins,readFilter,resolveAccountId,scopeItems,myzRate,accountingConversion,paymentAccountId,persistVerifiedPayment,ensureMyzCredit,runtimeMyzCredits,runtimeMyzDebits,augmentMyzBalance,spendableMyz,findOffer};
