const express = require('express');
const crypto = require('crypto');

const router = express.Router();

const DEFAULT_REPOSITORY = 'MyZubster-Ecosystem/myzubster';
const DEFAULT_CATEGORIES = ['bug', 'data-anomaly', 'documentation', 'improvement', 'environmental-observation', 'technical-debt'];
const DEFAULT_SEVERITIES = ['info', 'low', 'medium', 'high'];

function boolEnv(name, fallback = false) {
  const value = process.env[name];
  if (value === undefined) return fallback;
  return ['1', 'true', 'yes', 'on'].includes(String(value).toLowerCase());
}

function allowedRepositories() {
  return String(process.env.ZORGAX_GITHUB_ALLOWED_REPOS || DEFAULT_REPOSITORY)
    .split(',')
    .map(value => value.trim())
    .filter(Boolean);
}

function safeText(value, max) {
  return String(value || '').trim().slice(0, max);
}

function looksSensitive(text) {
  const value = String(text || '');
  return [
    /password\s*[:=]/i,
    /api[_ -]?key\s*[:=]/i,
    /secret\s*[:=]/i,
    /private[_ -]?key/i,
    /seed phrase/i,
    /recovery phrase/i,
    /-----BEGIN [A-Z ]*PRIVATE KEY-----/,
    /\b(?:ghp|github_pat|sk|pk)_[A-Za-z0-9_-]{16,}\b/
  ].some(pattern => pattern.test(value));
}

function validAdminKey(req) {
  const configured = process.env.ZORGAX_ADMIN_KEY;
  const supplied = req.get('x-zorgax-admin-key');
  if (!configured || !supplied) return false;
  const a = Buffer.from(String(configured));
  const b = Buffer.from(String(supplied));
  return a.length === b.length && crypto.timingSafeEqual(a, b);
}

function normalizeEvidence(evidence) {
  if (!Array.isArray(evidence)) return [];
  return evidence.slice(0, 10).map(item => ({
    source: safeText(item?.source || 'unspecified', 200),
    reference: safeText(item?.reference || '', 500),
    claim_class: ['verified', 'uncertain', 'speculative', 'fictional'].includes(item?.claim_class)
      ? item.claim_class
      : 'uncertain',
    note: safeText(item?.note || '', 1000)
  }));
}

function buildDraft(input = {}) {
  const title = safeText(input.title, 180);
  const summary = safeText(input.summary || input.body, 5000);
  const category = DEFAULT_CATEGORIES.includes(input.category) ? input.category : 'improvement';
  const severity = DEFAULT_SEVERITIES.includes(input.severity) ? input.severity : 'info';
  const repository = safeText(input.repository || DEFAULT_REPOSITORY, 200);
  const evidence = normalizeEvidence(input.evidence);
  const proposedAction = safeText(input.proposed_action, 2000);

  if (!title) throw new Error('title is required');
  if (!summary) throw new Error('summary is required');
  if (!allowedRepositories().includes(repository)) throw new Error('repository is not allowed');

  const allText = [title, summary, proposedAction, JSON.stringify(evidence)].join('\n');
  if (looksSensitive(allText)) throw new Error('possible credential or secret detected');

  const evidenceBlock = evidence.length
    ? evidence.map((item, index) => [
        `${index + 1}. **${item.source}** — \`${item.claim_class}\``,
        item.reference ? `   - Reference: ${item.reference}` : null,
        item.note ? `   - Note: ${item.note}` : null
      ].filter(Boolean).join('\n')).join('\n')
    : '_No external evidence supplied. Treat this proposal as unverified until a human checks it._';

  const body = [
    '> 🤖 **Zorgax automated proposal** — Zorgax is a virtual/fictional AI persona in the MyZubster ecosystem. This issue was generated by software and requires human review. It does not represent a decision, endorsement, partnership, contract, scientific conclusion, or institutional position.',
    '',
    '## Summary',
    summary,
    '',
    '## Classification',
    `- Category: \`${category}\``,
    `- Severity: \`${severity}\``,
    '- Decision authority: **human maintainers only**',
    '',
    '## Evidence / provenance',
    evidenceBlock,
    '',
    '## Proposed action',
    proposedAction || '_Zorgax has not proposed a specific implementation action._',
    '',
    '## Human review checklist',
    '- [ ] Verify the evidence and claim classes',
    '- [ ] Check for duplicate/existing issues',
    '- [ ] Confirm scope and priority',
    '- [ ] Decide whether to accept, reject, edit, or convert into implementation work',
    '',
    '---',
    '_Generated by ZORGAX-001. Automated content is a proposal, not proof._'
  ].join('\n');

  return {
    repository,
    title: `[ZORGAX] ${title}`,
    body,
    metadata: {
      entity: 'ZORGAX-001',
      virtual_identity: true,
      category,
      severity,
      evidence_count: evidence.length,
      requires_human_review: true
    }
  };
}

router.get('/status', (req, res) => {
  res.json({
    ok: true,
    entity: 'ZORGAX-001',
    capability: 'github-issue-agent',
    write_enabled: boolEnv('ZORGAX_GITHUB_WRITE_ENABLED', false),
    allowed_repositories: allowedRepositories(),
    human_review_required: true,
    publish_requires_admin_key: true,
    disclosure: 'Zorgax is a virtual/fictional AI persona; its issues are automated proposals only.'
  });
});

router.post('/propose', (req, res) => {
  try {
    const draft = buildDraft(req.body || {});
    res.status(200).json({ ok: true, published: false, draft });
  } catch (error) {
    res.status(400).json({ ok: false, error: error.message });
  }
});

router.post('/publish', async (req, res) => {
  try {
    if (!boolEnv('ZORGAX_GITHUB_WRITE_ENABLED', false)) {
      return res.status(403).json({ ok: false, error: 'Zorgax GitHub writes are disabled' });
    }
    if (!validAdminKey(req)) {
      return res.status(403).json({ ok: false, error: 'Valid x-zorgax-admin-key required' });
    }

    const token = process.env.ZORGAX_GITHUB_TOKEN || process.env.GITHUB_TOKEN;
    if (!token) {
      return res.status(503).json({ ok: false, error: 'GitHub token is not configured' });
    }

    const draft = buildDraft(req.body || {});
    const [owner, repo] = draft.repository.split('/');
    if (!owner || !repo) return res.status(400).json({ ok: false, error: 'Invalid repository format' });

    const response = await fetch(`https://api.github.com/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/issues`, {
      method: 'POST',
      headers: {
        Accept: 'application/vnd.github+json',
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json',
        'User-Agent': 'MyZubster-Zorgax-Issue-Agent',
        'X-GitHub-Api-Version': '2022-11-28'
      },
      body: JSON.stringify({ title: draft.title, body: draft.body })
    });

    const data = await response.json();
    if (!response.ok) {
      return res.status(response.status).json({
        ok: false,
        error: 'GitHub issue creation failed',
        github_status: response.status,
        github_message: data?.message || null
      });
    }

    res.status(201).json({
      ok: true,
      published: true,
      entity: 'ZORGAX-001',
      issue: {
        number: data.number,
        title: data.title,
        url: data.html_url,
        repository: draft.repository
      },
      human_review_required: true
    });
  } catch (error) {
    res.status(400).json({ ok: false, error: error.message });
  }
});

module.exports = router;
module.exports.buildDraft = buildDraft;
