const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const DEFAULT_GATEWAY = 'https://myzubster-gateway.vercel.app';
const MAX_SOURCES = 8;

function clampLimit(value, fallback = 5) { return Math.max(1, Math.min(Number(value) || fallback, MAX_SOURCES)); }
function cleanText(value, max = 6000) { return String(value || '').trim().slice(0, max); }
function dataIntent(text) { return /\b(salva|inserisci|registra|memorizza|aggiungi\s+(?:quest[oi]|dato|dati)|immetti)\b/i.test(String(text || '')); }
function inferCategory(text) { const value=String(text||'').toLowerCase(); if(/orto|pianta|semina|raccolto|terreno/.test(value))return'garden'; if(/robot|sensore|motore|elettronica/.test(value))return'robotics'; if(/lavoro|competenz|skill|candidato/.test(value))return'skills'; if(/ambiente|acqua|aria|suolo|temperatura|umidit/.test(value))return'environment'; if(/spesa|costo|prezzo|componente|pezzo/.test(value))return'procurement'; return'general'; }
function stableJson(value){if(Array.isArray(value))return`[${value.map(stableJson).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stableJson(value[key])}`).join(',')}}`;return JSON.stringify(value);}
function digestPreview(preview){return crypto.createHash('sha256').update(stableJson(preview)).digest('hex');}
function previewData(input){const raw=cleanText(input,12000);if(!raw)throw new Error('Dati mancanti');let parsed=null;try{parsed=JSON.parse(raw);}catch(_){}const preview={category:inferCategory(raw),title:raw.replace(/\s+/g,' ').slice(0,100)||'Dato inserito con Zorgax',data:parsed&&typeof parsed==='object'?parsed:{notes:raw},source:'zorgax_user_confirmed'};const digest=digestPreview(preview);return{preview,digest,confirmation:`CONFERMA ${digest.slice(0,8)}`,persistent_write_performed:false};}
async function braveSearch(query,limit){const key=process.env.BRAVE_SEARCH_API_KEY;if(!key)return[];const url=new URL('https://api.search.brave.com/res/v1/web/search');url.searchParams.set('q',query);url.searchParams.set('count',String(limit));const response=await fetch(url,{headers:{Accept:'application/json','X-Subscription-Token':key}});if(!response.ok)throw new Error(`Brave Search HTTP ${response.status}`);const json=await response.json();return(json.web?.results||[]).slice(0,limit).map((item,index)=>({label:`B${index+1}`,provider:'brave',title:item.title,url:item.url,snippet:cleanText(item.description,700)}));}
async function tavilySearch(query,limit){const key=process.env.TAVILY_API_KEY;if(!key)return[];const response=await fetch('https://api.tavily.com/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:key,query,max_results:limit,search_depth:'advanced',include_answer:false})});if(!response.ok)throw new Error(`Tavily HTTP ${response.status}`);const json=await response.json();return(json.results||[]).slice(0,limit).map((item,index)=>({label:`T${index+1}`,provider:'tavily',title:item.title,url:item.url,snippet:cleanText(item.content,700)}));}
async function wikipediaSearch(query,limit){const url=new URL('https://en.wikipedia.org/w/api.php');url.searchParams.set('action','query');url.searchParams.set('generator','search');url.searchParams.set('gsrsearch',query);url.searchParams.set('gsrlimit',String(limit));url.searchParams.set('prop','extracts|info');url.searchParams.set('inprop','url');url.searchParams.set('exintro','1');url.searchParams.set('explaintext','1');url.searchParams.set('format','json');url.searchParams.set('origin','*');const response=await fetch(url,{headers:{'User-Agent':'MyZubster-Zorgax/1.0'}});if(!response.ok)throw new Error(`Wikipedia HTTP ${response.status}`);const json=await response.json();return Object.values(json.query?.pages||{}).slice(0,limit).map((item,index)=>({label:`W${index+1}`,provider:'wikipedia',title:item.title,url:item.fullurl,snippet:cleanText(item.extract,700)}));}
function looksTimeSensitive(text){return /\b(today|tonight|current|currently|latest|news|recent|now|oggi|stasera|attuale|attualmente|ultim[oaie]|notizie|recente|ora|adesso|president|prime minister|pope|papa|election|elezioni|price|prezzo|market|mercato)\b/i.test(String(text||''));}
async function googleNewsSearch(){return[];}
async function searchWeb(query,requestedLimit=5){const cleanQuery=cleanText(query,500);if(!cleanQuery)return{query:'',sources:[],errors:[],live_search_available:false,providers_used:[]};const limit=clampLimit(requestedLimit);const errors=[];const groups=await Promise.all([braveSearch(cleanQuery,limit).catch(e=>{errors.push(e.message);return[];}),tavilySearch(cleanQuery,limit).catch(e=>{errors.push(e.message);return[];}),wikipediaSearch(cleanQuery,Math.min(limit,4)).catch(e=>{errors.push(e.message);return[];})]);const seen=new Set();const sources=groups.flat().filter(s=>{if(!s.url||seen.has(s.url))return false;seen.add(s.url);return true;}).slice(0,limit);return{query:cleanQuery,sources,errors,live_search_available:sources.length>0,providers_used:[...new Set(sources.map(s=>s.provider).filter(Boolean))]};}

function loadZorgaxPersona(){
  try{return fs.readFileSync(path.join(process.cwd(),'agents','zorgax','SYSTEM_PROMPT.md'),'utf8');}
  catch(_){return 'You are Zorgax, the MyZubster product copilot. MyZubster is a live evolving open-source ecosystem. Be concise, product-first, and guide users to Marketplace, Seller, Metaverse, LIFE Pilot, or Community.';}
}

async function askGeneralAI(message,sources=[],history=[],webRequested=false){
  const gateway=String(process.env.ZORGAX_PUBLIC_AI_URL||DEFAULT_GATEWAY).replace(/\/$/,'');
  const sourceContext=sources.length?`\n\nFONTI WEB RECUPERATE:\n${sources.map(s=>`[${s.label}] ${s.title}\n${s.url}\n${s.snippet}`).join('\n\n')}`:'';
  const persona=loadZorgaxPersona();
  const runtime=`\n\nRUNTIME PRODUCT FACTS:\n- myzubster.com is a public live web interface. Never claim MyZubster is unpublished, local-only, or repository-only.\n- Current user paths include Marketplace, Seller through Marketplace, Metaverse, LIFE Pilot, Community/login and open-source contribution.\n- MYZ is internal accounting/reward; it is distinct from commercial Marketplace/Seller payment flows.\n- For newcomer questions, lead with what the user can do now. Keep the answer concise and finish with concrete next actions.\n- Do not lead with architecture, IPFS, bounty mechanics, personal identities or long MVP disclaimers unless asked.`;
  const prompt=`${persona}${runtime}\n\nUSER MESSAGE:\n${cleanText(message)}${sourceContext}`;
  const response=await fetch(`${gateway}/api/zargox/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:prompt,useWeb:false,history:Array.isArray(history)?history.slice(-12):[]})});
  const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`AI gateway HTTP ${response.status}`);return json.response||json.message||json.answer||'';
}
async function answer({message,useWeb=true,history=[],limit=5}){const text=cleanText(message);if(!text)throw new Error('Messaggio mancante');if(dataIntent(text)){const dataPreview=previewData(text.replace(/^.*?\b(?:salva|inserisci|registra|memorizza|immetti)\b\s*/i,''));return{response:`Ho preparato l'anteprima dei dati. Non ho salvato nulla. Per renderli persistenti devi confermare esplicitamente con: ${dataPreview.confirmation}`,data_preview:dataPreview,action_required:'human_confirmation',sources:[]};}const research=useWeb?await searchWeb(text,limit):{query:text,sources:[],errors:[],live_search_available:false,providers_used:[]};const response=await askGeneralAI(text,research.sources,history,useWeb);return{response,sources:research.sources,search_errors:research.errors,web_research_requested:Boolean(useWeb),web_research_available:Boolean(research.live_search_available),web_providers_used:research.providers_used,action_required:null};}
module.exports={answer,searchWeb,previewData,digestPreview,dataIntent,inferCategory,looksTimeSensitive,googleNewsSearch};
