import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import WalletHubPanel from'../components/WalletHubPanel';
import{trackConversion,trackConversionOnce}from'../analytics/conversionAnalytics';
import{getLanguage,LANGUAGE_NAMES,setLanguage}from'../i18n';

const categories=['seeds','plants','produce','clothing','accessories','event_equipment','tools','services','volunteering','pet_adoption','pet_lost_found','pet_services'];
const demoCategories=[...categories,'art','wellness','university_course','thesis_project','research_project','internship'];
const currencies=['FREE','BARTER','MYZ','ETH','BTC','XMR','TARI'];
const DEMO_SELLERS=[
  {id:'demo-kefir',icon:'🥛',name:'Kefir Lab Demo',category:'produce',location:'Emilia-Romagna',offer:'Grani di kefir e guida introduttiva',description:'Esempio di scambio locale con istruzioni di conservazione e ritiro concordato.',price:'BARTER',requests:4,availability:'Su appuntamento',details:[['Tipo','Scambio alimentare'],['Consegna','Ritiro locale']]},
  {id:'demo-repair',icon:'🧰',name:'Circular Repair Demo',category:'services',location:'Cesena',offer:'Riparazione collaborativa di piccoli oggetti',description:'Sessione dimostrativa di diagnosi e riparazione con approccio circolare.',price:'15 MYZ',requests:7,availability:'Sabato',details:[['Durata','60 minuti'],['Modalità','In presenza']]},
  {id:'demo-seeds',icon:'🌾',name:'Seed Commons Demo',category:'seeds',location:'Italia',offer:'Scambio di semi locali tracciabili',description:'Lotto dimostrativo con provenienza e stagione consigliata.',price:'FREE',requests:3,availability:'Primavera',details:[['Provenienza','Locale'],['Scambio','Community']]},
  {id:'demo-sound-system',icon:'🔊',name:'Sound System Collective Demo',category:'tools',location:'Italia',offer:'Vendita o noleggio di un sound system artigianale completo',description:'Configurazione dimostrativa per eventi autorizzati, con trasporto da concordare.',price:'1.200 EUR',requests:9,availability:'Weekend',details:[['Potenza','Demo 6 kW'],['Uso','Eventi autorizzati']]},
  {id:'demo-audio-gear',icon:'🎚️',name:'Underground Audio Gear Demo',category:'tools',location:'Bologna',offer:'Mixer, amplificatori, cavi e componenti audio usati',description:'Set dimostrativo di attrezzatura usata verificabile prima dello scambio.',price:'BARTER',requests:6,availability:'Disponibile',details:[['Condizione','Usato'],['Scambio','Baratto']]},
  {id:'demo-event-tech',icon:'💡',name:'Free Party Tech Demo',category:'services',location:'Europa',offer:'Montaggio audio, luci e assistenza tecnica per eventi culturali',description:'Servizio demo per eventi legali e autorizzati, dalla preparazione al disallestimento.',price:'180 EUR',requests:5,availability:'Su calendario',details:[['Servizio','Audio + luci'],['Sicurezza','Evento autorizzato']]},
  {id:'demo-subculture-wear',icon:'🧥',name:'Subculture Wear Demo',category:'clothing',location:'Europa',offer:'Indumenti, patch, borse e accessori legati alle culture underground',description:'Capsule demo di abbigliamento recuperato e personalizzato.',price:'35 EUR',requests:8,availability:'Disponibile',details:[['Produzione','Upcycling'],['Taglia','Variabile']]},
  {id:'demo-event-sound-rental',icon:'🎛️',name:'Mobile Sound Rental Demo',category:'event_equipment',location:'Italia',offer:'Noleggio impianto audio completo per eventi con trasporto e montaggio',description:'Pacchetto dimostrativo con consegna, setup e ritiro.',price:'350 EUR',requests:11,availability:'Weekend',details:[['Include','Trasporto + setup'],['Uso','Eventi autorizzati']]},
  {id:'demo-dj-package',icon:'🎧',name:'DJ & Crew Demo',category:'services',location:'Italia',offer:'DJ set, selezione musicale e supporto tecnico per eventi',description:'Crew dimostrativa per programmazione musicale e supporto tecnico.',price:'220 EUR',requests:7,availability:'Su calendario',details:[['Durata','4 ore demo'],['Formato','DJ + supporto']]},
  {id:'demo-event-machines',icon:'🌫️',name:'Event Machines Demo',category:'event_equipment',location:'Emilia-Romagna',offer:'Noleggio luci, macchina del fumo, proiettori, generatori e attrezzature per eventi',description:'Catalogo dimostrativo di attrezzature per produzioni autorizzate.',price:'BARTER',requests:6,availability:'Disponibile',details:[['Inventario','Luci + effetti'],['Scambio','Baratto']]},
  {id:'demo-plants',icon:'🪴',name:'Community Plant Nursery Demo',category:'plants',location:'Italia',offer:'Piante locali con scheda di cura e provenienza documentata',description:'Pianta dimostrativa accompagnata da indicazioni di cura e provenienza.',price:'FREE',requests:3,availability:'Disponibile',details:[['Specie','Pianta locale demo'],['Cura','Scheda inclusa']]},
  {id:'demo-accessories',icon:'🎒',name:'Upcycled Accessories Demo',category:'accessories',location:'Europa',offer:'Borse, patch e accessori realizzati con materiali recuperati',description:'Accessori demo realizzati da materiali riutilizzati.',price:'20 MYZ',requests:5,availability:'Disponibile',details:[['Materiale','Recuperato'],['Produzione','Artigianale']]},
  {id:'demo-volunteering',icon:'🤝',name:'Community Garden Volunteers Demo',category:'volunteering',location:'Emilia-Romagna',offer:'Supporto volontario per cura degli orti e documentazione delle attività',description:'Turno demo di volontariato: nessun pagamento, solo disponibilità e coordinamento.',price:'FREE',requests:4,availability:'Sabato mattina',details:[['Impegno','2 ore'],['Attività','Cura orto e documentazione'],['Compenso','Nessuno · volontariato']]},
  {id:'demo-pet-adoption',icon:'🐶',name:'Responsible Pet Adoption Demo',category:'pet_adoption',location:'Italia',offer:'Profilo dimostrativo per adozione responsabile tramite associazione verificata',description:'Esempio di scheda adozione con contatto mediato da associazione. Nessun acquisto di animali.',price:'FREE',requests:6,availability:'Colloquio richiesto',details:[['Animale','Cane adulto demo'],['Età','4 anni'],['Referente','Associazione demo'],['Procedura','Colloquio + verifica adozione']]},
  {id:'demo-pet-lost-found',icon:'🔎',name:'Lost & Found Pet Alert Demo',category:'pet_lost_found',location:'Italia',offer:'Segnalazione dimostrativa con zona approssimativa e contatto autorizzato',description:'Segnalazione demo progettata per proteggere dati sensibili e posizione esatta.',price:'FREE',requests:2,availability:'Segnalazione aperta',details:[['Stato','Trovato'],['Area','Zona approssimativa'],['Privacy','Posizione esatta non pubblicata']]},
  {id:'demo-pet-services',icon:'🐾',name:'Local Pet Care Demo',category:'pet_services',location:'Cesena',offer:'Passeggiate e assistenza quotidiana per animali domestici',description:'Servizio demo di pet care con disponibilità e area di copertura.',price:'12 EUR',requests:5,availability:'Lun–Ven',details:[['Servizio','Passeggiata 45 min'],['Copertura','Cesena'],['Animali','Cani e gatti']]},
  {id:'demo-preserves',icon:'🍅',name:'Dispensa Locale Demo',category:'produce',location:'Emilia-Romagna',offer:'Conserve, sughi e marmellate fatti in casa',description:'Esempio di produzione locale in piccoli lotti con ingredienti e modalità di ritiro dichiarati.',price:'BARTER',requests:5,availability:'Disponibile',details:[['Prodotti','Sugo, conserve e marmellate'],['Ritiro','Locale']]},
  {id:'demo-plumber',icon:'🔧',name:'Cerco Idraulico Demo',category:'services',location:'Cesena',offer:'Cerco idraulico per perdita sotto il lavello',description:'Richiesta demo per una perdita visibile dal sifone sotto il lavello, con intervento da concordare.',price:'45 EUR',requests:8,availability:'Appena possibile',details:[['Problema','Perdita sotto lavello'],['Intervento','Diagnosi e riparazione']]},
  {id:'demo-pc-repair',icon:'💻',name:'Cerco Tecnico PC Demo',category:'services',location:'Ravenna',offer:'Cerco tecnico per computer guasto',description:'Richiesta demo per diagnosticare un computer che non funziona correttamente e valutare la riparazione.',price:'35 EUR',requests:6,availability:'Questa settimana',details:[['Dispositivo','Computer portatile'],['Richiesta','Diagnosi + riparazione']]},
  {id:'demo-network-tech',icon:'📡',name:'Cerco Sistemista Demo',category:'services',location:'Bologna',offer:'Cerco tecnico di rete per modem e Wi-Fi senza connessione',description:'Richiesta demo per verificare modem, router e rete domestica quando Internet non è disponibile.',price:'50 EUR',requests:7,availability:'Su appuntamento',details:[['Problema','Connessione assente'],['Rete','Modem + router + Wi-Fi']]},
  {id:'demo-mason',icon:'🧱',name:'Cerco Muratore Demo',category:'services',location:'Emilia-Romagna',offer:'Cerco muratore per muro e intonaco danneggiato',description:'Richiesta demo per ripristinare una zona di intonaco deteriorata e rifinire la parete.',price:'120 EUR',requests:4,availability:'Da concordare',details:[['Lavoro','Ripristino intonaco'],['Area','Parete interna']]},
  {id:'demo-electrician',icon:'⚡',name:'Cerco Elettricista Demo',category:'services',location:'Cesena',offer:'Cerco elettricista per presa elettrica guasta',description:'Richiesta demo per controllare una presa non funzionante e mettere in sicurezza il collegamento.',price:'60 EUR',requests:5,availability:'Questa settimana',details:[['Problema','Presa guasta'],['Intervento','Controllo e ripristino']]},
  {id:'demo-art-original',icon:'🎨',name:'Arte & Artisti Demo',category:'art',location:'Italia',offer:'Dipinto originale in vendita',description:'Annuncio demo di un artista indipendente che propone un dipinto originale e il contatto diretto con chi è interessato.',price:'180 EUR',requests:6,availability:'Disponibile',details:[['Opera','Dipinto originale'],['Autore','Artista indipendente']]},
  {id:'demo-wellness-braids',icon:'💇',name:'Treccine & Rasta Demo',category:'wellness',location:'Emilia-Romagna',offer:'Rasta, treccine e acconciature a domicilio',description:'Servizio demo di cura personale non medica con appuntamento a domicilio.',price:'45 EUR',requests:9,availability:'Su appuntamento',details:[['Servizio','Treccine e acconciature'],['Modalità','A domicilio']]},
  {id:'demo-wellness-nails',icon:'💅',name:'Nail Art Demo',category:'wellness',location:'Cesena',offer:'Nail art e manicure a domicilio',description:'Servizio demo di manicure e decorazione unghie con appuntamento concordato.',price:'30 EUR',requests:8,availability:'Lun–Sab',details:[['Servizio','Manicure + nail art'],['Modalità','A domicilio']]},
  {id:'demo-university-course',icon:'🎓',name:'Corso Open Source Demo',category:'university_course',location:'Online / Italia',offer:'Laboratorio introduttivo GitHub e collaborazione open source',description:'Percorso demo con repository, issue guidate, tutoraggio e revisione del lavoro. Nessun credito universitario automatico.',price:'FREE',requests:12,availability:'Prossima coorte',details:[['Formato','Online + repository GitHub'],['Validazione','Docente/ateneo se autorizzato']]},
  {id:'demo-thesis',icon:'📘',name:'Tesi MyZubster Demo',category:'thesis_project',location:'Italia',offer:'Proposta di tesi su AI, comunità ed economia circolare',description:'Tema dimostrativo da concordare con un relatore universitario, con codice e documentazione pubblica quando possibile.',price:'FREE',requests:5,availability:'Candidature aperte',details:[['Output','Tesi + repository'],['Approvazione','Relatore richiesta']]},
  {id:'demo-research',icon:'🔬',name:'Ricerca Riproducibile Demo',category:'research_project',location:'Europa',offer:'Studio interdisciplinare con dataset autorizzati e protocollo GitHub',description:'Progetto demo per ricercatori e studenti: dati con provenienza, metodo versionato e revisione umana.',price:'FREE',requests:8,availability:'Collaboratori cercati',details:[['Metodo','Riproducibile'],['Dati','Autorizzati e minimizzati']]},
  {id:'demo-internship',icon:'🧪',name:'Tirocinio Open Source Demo',category:'internship',location:'Ibrido',offer:'Percorso pratico su issue, test e pull request MyZubster',description:'Tirocinio dimostrativo: il riconoscimento formale richiede accordo e approvazione dell’università.',price:'FREE',requests:10,availability:'Da concordare',details:[['Attività','Issue + test + PR'],['Riconoscimento','Non automatico']]},
  {id:'demo-dog-sitter-request',icon:'🐕',name:'Cerco Dog Sitter Demo',category:'pet_services',location:'Emilia-Romagna',offer:'Cerco dog sitter affidabile per il mio cane',description:'Richiesta demo per trovare una persona disponibile a occuparsi del cane per alcune ore.',price:'15 EUR',requests:7,availability:'Weekend',details:[['Animale','Cane'],['Servizio','Custodia e passeggiata']]}
];
const DEMO_IMAGES={
  'demo-kefir':'/images/marketplace/demo/produce-kefir.png',
  'demo-repair':'/images/marketplace/demo/circular-repair.png',
  'demo-seeds':'/images/marketplace/demo/seeds-semi-locali.png',
  'demo-plants':'/images/marketplace/demo/plants-piantine-orto.png',
  'demo-pet-lost-found':'/images/marketplace/demo/animals-cane-smarrito-max.jpg',
  'demo-pet-services':'/images/marketplace/demo/animals-dog-sitter-leo.jpg',
  'demo-preserves':'/images/marketplace/demo/produce-conserve.png',
  'demo-plumber':'/images/marketplace/demo/idraulico-perdita-lavello.png',
  'demo-pc-repair':'/images/marketplace/demo/tecnico-pc-computer-guasto.png',
  'demo-network-tech':'/images/marketplace/demo/sistemista-router-offline.png',
  'demo-mason':'/images/marketplace/demo/muratore-muro-danneggiato.png',
  'demo-electrician':'/images/marketplace/demo/elettricista-presa-guasta.png',
  'demo-art-original':'/images/marketplace/demo/arte-dipinto-originale.png',
  'demo-wellness-braids':'/images/marketplace/demo/benessere-rasta-treccine.png',
  'demo-wellness-nails':'/images/marketplace/demo/benessere-nail-art.png',
  'demo-dog-sitter-request':'/images/marketplace/demo/animals-cerco-dog-sitter.jpg'
};

function demoPaymentMode(price=''){if(price==='FREE')return'FREE';if(price==='BARTER')return'BARTER';if(/MYZ/i.test(price))return'MYZ';if(/EUR|€/i.test(price))return'EUR';return'OTHER'}
function filterDemoSellers(rows,{category='',location='',query='',payment=''}){const q=query.trim().toLowerCase(),place=location.trim().toLowerCase();return rows.filter(row=>(!category||row.category===category)&&(!place||row.location.toLowerCase().includes(place))&&(!payment||demoPaymentMode(row.price)===payment)&&(!q||[row.name,row.offer,row.description,row.category,row.location].some(v=>String(v||'').toLowerCase().includes(q))))}
function isDemoDeepLink(search=''){return new URLSearchParams(search).get('demo')==='1'}

const BASE_COPY={title:'Publish your offer and receive real requests',intro:'Create a Seller space for products, services or projects. Browsing stays free.',seller:'Open your MyZubster Seller space',activate:'Become a Seller · €9.90/month',active:'Seller active',publish:'Publish listing',close:'Close',desc:'Description',place:'Location',price:'Price',send:'Publish',all:'All categories',filter:'Filter location',refresh:'Refresh',loading:'Loading listings…',empty:'No public listings yet',first:'You can be the first to publish one.',request:'Request',free:'Free',barter:'Barter',login:'Sign in before becoming a Seller.',checkout:'Opening Stripe Checkout…',published:'Listing published.',why:'What you get',benefits:['Publish products, services and projects','Manage listings and availability','Receive requests from the community','Build reputation from completed exchanges'],buyer:'Buying and discovering stays free.',cancel:'Monthly subscription. Cancel from your account.',fromZorgax:'Zorgax brought you here: turn your idea into a real Seller space.',success:'Payment received. We are verifying and activating your Seller profile.',cancelled:'Checkout cancelled. No charge was made; you can try again when ready.',activateTrial:'Start {days} days free',trialTerms:'Eligible new Sellers are not charged for {days} days; then €9.90/month.',cohort:'Founding Seller cohort',cohortText:'We are forming the first group of real offers and measuring verifiable requests. No sales are promised.',wallet:'Wallets and digital payments',formTitle:'Title',demoTitle:'Marketplace Demo v2',demoNote:'Interactive demonstration profiles. Demo listings are sample content and never create real transactions.',demoBadge:'DEMO',demoOffer:'Example offer',demoRequests:'simulated requests',demoTry:'Create your real Seller',demoSearch:'Search demos',demoPayment:'Demo payment type',demoAllPayments:'All demo modes',demoDetails:'Open demo',demoAvailability:'Availability',demoRequest:'Try request flow',demoWarning:'DEMO ONLY — no order, payment, message or personal data is created.',demoReview:'Review simulated request',demoConfirm:'Confirm simulated request',demoConfirmed:'Demo request confirmed locally. Nothing was sent and no payment was created.',demoBack:'Back to demos',demoLocalReview:'This confirmation changes only the demo state in your browser.',noDemoMatches:'No demo matches the selected filters.',closeDemo:'Close demo'};
const C={
  en:BASE_COPY,
  it:{...BASE_COPY,title:'Pubblica la tua offerta e ricevi richieste reali',intro:'Crea uno spazio Seller per prodotti, servizi o progetti. Il Marketplace resta gratuito per chi cerca e acquista.',seller:'Apri il tuo spazio Seller MyZubster',activate:'Diventa Seller · 9,90 €/mese',active:'Seller attivo',publish:'Pubblica annuncio',close:'Chiudi',desc:'Descrizione',place:'Località',price:'Prezzo',send:'Pubblica',all:'Tutte le categorie',filter:'Filtra località',refresh:'Aggiorna',loading:'Caricamento annunci…',empty:'Nessun annuncio pubblico per ora',first:'Puoi essere il primo a pubblicarne uno.',request:'Richiedi',free:'Gratis',barter:'Baratto',login:'Per diventare Seller devi prima accedere a MyZubster.',checkout:'Apertura Stripe Checkout…',published:'Annuncio pubblicato.',why:'Cosa ottieni',benefits:['Pubblica prodotti, servizi e progetti','Gestisci annunci e disponibilità','Ricevi richieste dalla community','Costruisci reputazione dagli scambi completati'],buyer:'Per chi compra e scopre il Marketplace resta gratuito.',cancel:'Abbonamento mensile. Puoi annullare dal tuo account.',fromZorgax:'Zorgax ti ha portato qui: ora puoi trasformare la tua idea in uno spazio Seller reale.',success:'Pagamento ricevuto. Stiamo verificando e attivando il tuo profilo Seller.',activateTrial:'Inizia {days} giorni gratis',trialTerms:'Per i nuovi Seller idonei: nessun addebito per {days} giorni, poi 9,90 €/mese.',cohort:'Cohort Founding Seller',cohortText:'Stiamo formando il primo gruppo di offerte reali e raccogliendo richieste verificabili. Nessuna promessa di vendite.',wallet:'Wallet e pagamenti digitali',formTitle:'Titolo',demoTitle:'Marketplace Demo v2',demoNote:'Profili dimostrativi interattivi. Gli annunci demo sono contenuti di esempio e non creano transazioni reali.',demoOffer:'Offerta di esempio',demoRequests:'richieste simulate',demoTry:'Crea il tuo Seller reale',demoSearch:'Cerca nelle demo',demoPayment:'Tipo pagamento demo',demoAllPayments:'Tutte le modalità demo',demoDetails:'Apri demo',demoAvailability:'Disponibilità',demoRequest:'Prova flusso richiesta',demoWarning:'SOLO DEMO — non viene creato alcun ordine, pagamento, messaggio o dato personale.',demoReview:'Rivedi richiesta simulata',demoConfirm:'Conferma richiesta simulata',demoConfirmed:'Richiesta demo confermata solo localmente. Non è stato inviato nulla e non è stato creato alcun pagamento.',demoBack:'Torna alle demo',demoLocalReview:'Questa conferma modifica solo lo stato della demo nel browser.',noDemoMatches:'Nessuna demo corrisponde ai filtri selezionati.',closeDemo:'Chiudi demo'},
  es:{...BASE_COPY,title:'Publica tu oferta y recibe solicitudes reales',intro:'Crea un espacio Seller para productos, servicios o proyectos. Explorar el Marketplace sigue siendo gratis.',seller:'Abre tu espacio Seller de MyZubster',activate:'Hazte Seller · 9,90 €/mes',active:'Seller activo',publish:'Publicar anuncio',close:'Cerrar',desc:'Descripción',place:'Ubicación',price:'Precio',send:'Publicar',all:'Todas las categorías',filter:'Filtrar ubicación',refresh:'Actualizar',loading:'Cargando anuncios…',empty:'Todavía no hay anuncios públicos',first:'Puedes ser la primera persona en publicar uno.',request:'Solicitar',free:'Gratis',barter:'Trueque',login:'Inicia sesión antes de convertirte en Seller.',checkout:'Abriendo Stripe Checkout…',published:'Anuncio publicado.',why:'Qué obtienes',benefits:['Publica productos, servicios y proyectos','Gestiona anuncios y disponibilidad','Recibe solicitudes de la comunidad','Construye reputación con intercambios completados'],buyer:'Comprar y descubrir en el Marketplace sigue siendo gratis.',cancel:'Suscripción mensual. Puedes cancelarla desde tu cuenta.',fromZorgax:'Zorgax te trajo aquí: convierte tu idea en un espacio Seller real.',success:'Pago recibido. Estamos verificando y activando tu perfil Seller.',activateTrial:'Empieza {days} días gratis',trialTerms:'Los nuevos Seller elegibles no pagan durante {days} días; después, 9,90 €/mes.',cohort:'Cohorte Founding Seller',cohortText:'Estamos formando el primer grupo de ofertas reales y midiendo solicitudes verificables. No se prometen ventas.',wallet:'Wallets y pagos digitales',formTitle:'Título',demoTitle:'Marketplace Demo v2',demoNote:'Perfiles interactivos de demostración. Los anuncios demo son contenido de ejemplo y nunca crean transacciones reales.',demoBadge:'DEMO',demoOffer:'Oferta de ejemplo',demoRequests:'solicitudes simuladas',demoTry:'Crea tu Seller real',demoSearch:'Buscar demos',demoPayment:'Tipo de pago demo',demoAllPayments:'Todos los modos demo',demoDetails:'Abrir demo',demoAvailability:'Disponibilidad',demoRequest:'Probar flujo de solicitud',demoWarning:'SOLO DEMO — no se crea ningún pedido, pago, mensaje ni dato personal.',demoReview:'Revisar solicitud simulada',demoConfirm:'Confirmar solicitud simulada',demoConfirmed:'Solicitud demo confirmada solo localmente. No se envió nada ni se creó ningún pago.',demoBack:'Volver a las demos',demoLocalReview:'Esta confirmación solo cambia el estado de la demo en tu navegador.',noDemoMatches:'Ninguna demo coincide con los filtros seleccionados.',closeDemo:'Cerrar demo'},
  fr:{...BASE_COPY,title:'Publiez votre offre et recevez de vraies demandes',intro:'Créez un espace Seller pour des produits, services ou projets. La consultation du Marketplace reste gratuite.',seller:'Ouvrez votre espace Seller MyZubster',activate:'Devenir Seller · 9,90 €/mois',active:'Seller actif',publish:'Publier une annonce',close:'Fermer',desc:'Description',place:'Localisation',price:'Prix',send:'Publier',all:'Toutes les catégories',filter:'Filtrer la localisation',refresh:'Actualiser',loading:'Chargement des annonces…',empty:'Aucune annonce publique pour le moment',first:'Vous pouvez être la première personne à en publier une.',request:'Demander',free:'Gratuit',barter:'Troc',login:'Connectez-vous avant de devenir Seller.',checkout:'Ouverture de Stripe Checkout…',published:'Annonce publiée.',why:'Ce que vous obtenez',benefits:['Publiez des produits, services et projets','Gérez les annonces et les disponibilités','Recevez des demandes de la communauté','Construisez votre réputation grâce aux échanges réalisés'],buyer:'Acheter et découvrir le Marketplace reste gratuit.',cancel:'Abonnement mensuel. Annulable depuis votre compte.',fromZorgax:'Zorgax vous a amené ici : transformez votre idée en véritable espace Seller.',success:'Paiement reçu. Nous vérifions et activons votre profil Seller.',activateTrial:'Commencer {days} jours gratuitement',trialTerms:'Les nouveaux Seller éligibles ne sont pas facturés pendant {days} jours, puis 9,90 €/mois.',cohort:'Cohorte Founding Seller',cohortText:'Nous constituons le premier groupe d’offres réelles et mesurons des demandes vérifiables. Aucune vente n’est garantie.',wallet:'Wallets et paiements numériques',formTitle:'Titre',demoTitle:'Marketplace Demo v2',demoNote:'Profils de démonstration interactifs. Les annonces demo sont des exemples et ne créent jamais de transaction réelle.',demoBadge:'DEMO',demoOffer:'Offre exemple',demoRequests:'demandes simulées',demoTry:'Créez votre vrai Seller',demoSearch:'Rechercher dans les demos',demoPayment:'Type de paiement demo',demoAllPayments:'Tous les modes demo',demoDetails:'Ouvrir la demo',demoAvailability:'Disponibilité',demoRequest:'Tester le parcours de demande',demoWarning:'DEMO UNIQUEMENT — aucune commande, paiement, message ou donnée personnelle n’est créé.',demoReview:'Vérifier la demande simulée',demoConfirm:'Confirmer la demande simulée',demoConfirmed:'Demande demo confirmée uniquement localement. Rien n’a été envoyé et aucun paiement n’a été créé.',demoBack:'Retour aux demos',demoLocalReview:'Cette confirmation modifie uniquement l’état de la demo dans votre navigateur.',noDemoMatches:'Aucune demo ne correspond aux filtres sélectionnés.',closeDemo:'Fermer la demo'},
  de:{...BASE_COPY,title:'Veröffentliche dein Angebot und erhalte echte Anfragen',intro:'Erstelle einen Seller-Bereich für Produkte, Dienstleistungen oder Projekte. Das Durchsuchen des Marketplace bleibt kostenlos.',seller:'Öffne deinen MyZubster Seller-Bereich',activate:'Seller werden · 9,90 €/Monat',active:'Seller aktiv',publish:'Anzeige veröffentlichen',close:'Schließen',desc:'Beschreibung',place:'Standort',price:'Preis',send:'Veröffentlichen',all:'Alle Kategorien',filter:'Standort filtern',refresh:'Aktualisieren',loading:'Anzeigen werden geladen…',empty:'Noch keine öffentlichen Anzeigen',first:'Du kannst die erste Anzeige veröffentlichen.',request:'Anfragen',free:'Kostenlos',barter:'Tausch',login:'Melde dich an, bevor du Seller wirst.',checkout:'Stripe Checkout wird geöffnet…',published:'Anzeige veröffentlicht.',why:'Das erhältst du',benefits:['Produkte, Dienstleistungen und Projekte veröffentlichen','Anzeigen und Verfügbarkeit verwalten','Anfragen aus der Community erhalten','Reputation durch abgeschlossene Austausche aufbauen'],buyer:'Kaufen und Entdecken im Marketplace bleibt kostenlos.',cancel:'Monatliches Abo. Du kannst es in deinem Konto kündigen.',fromZorgax:'Zorgax hat dich hierher geführt: Verwandle deine Idee in einen echten Seller-Bereich.',success:'Zahlung erhalten. Wir prüfen und aktivieren dein Seller-Profil.',activateTrial:'{days} Tage kostenlos starten',trialTerms:'Berechtigte neue Seller zahlen {days} Tage nichts, danach 9,90 €/Monat.',cohort:'Founding-Seller-Kohorte',cohortText:'Wir bilden die erste Gruppe echter Angebote und messen überprüfbare Anfragen. Verkäufe werden nicht versprochen.',wallet:'Wallets und digitale Zahlungen',formTitle:'Titel',demoTitle:'Marketplace Demo v2',demoNote:'Interaktive Demoprofile. Demo-Anzeigen sind Beispielinhalte und erzeugen niemals echte Transaktionen.',demoBadge:'DEMO',demoOffer:'Beispielangebot',demoRequests:'simulierte Anfragen',demoTry:'Erstelle deinen echten Seller',demoSearch:'Demos durchsuchen',demoPayment:'Demo-Zahlungsart',demoAllPayments:'Alle Demo-Modi',demoDetails:'Demo öffnen',demoAvailability:'Verfügbarkeit',demoRequest:'Anfrageablauf testen',demoWarning:'NUR DEMO — es werden keine Bestellung, Zahlung, Nachricht oder personenbezogenen Daten erstellt.',demoReview:'Simulierte Anfrage prüfen',demoConfirm:'Simulierte Anfrage bestätigen',demoConfirmed:'Demo-Anfrage nur lokal bestätigt. Es wurde nichts gesendet und keine Zahlung erstellt.',demoBack:'Zurück zu den Demos',demoLocalReview:'Diese Bestätigung ändert nur den Demo-Status in deinem Browser.',noDemoMatches:'Keine Demo entspricht den ausgewählten Filtern.',closeDemo:'Demo schließen'}
};

function authHeaders(extra={}){const token=localStorage.getItem('myzubster-token');return{...extra,...(token?{Authorization:`Bearer ${token}`}:{})}}

function MarketplacePage(){
  const[lang,setLangState]=useState(getLanguage),t=C[lang]||C.en,[listings,setListings]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[category,setCategory]=useState(''),[location,setLocation]=useState(''),[showCreate,setShowCreate]=useState(false),[form,setForm]=useState({title:'',category:'services',description:'',location:'',price:'',currency:'FREE'}),[message,setMessage]=useState(''),[sellerPlan,setSellerPlan]=useState(null),[sellerState,setSellerState]=useState(null),[demoQuery,setDemoQuery]=useState(''),[demoPayment,setDemoPayment]=useState(''),[selectedDemo,setSelectedDemo]=useState(null),[demoFlow,setDemoFlow]=useState('idle');
  const params=useMemo(()=>new URLSearchParams(window.location.search),[]);
  const demoDeepLink=useMemo(()=>isDemoDeepLink(window.location.search),[]);
  const demoSectionRef=useRef(null),demoDialogRef=useRef(null);
  const sellerSource=params.get('from')||params.get('utm_source')||'';
  const fromZorgax=sellerSource.toLowerCase().includes('zorgax')||params.get('intent')==='seller';
  const filteredDemos=useMemo(()=>filterDemoSellers(DEMO_SELLERS,{category,location,query:demoQuery,payment:demoPayment}),[category,location,demoQuery,demoPayment]);

  const load=useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams();if(category)p.set('category',category);if(location)p.set('location',location);const r=await fetch(`/api/listings?${p}`),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||'Marketplace unavailable');setListings(Array.isArray(d.listings)?d.listings:[])}catch(e){setError(e.message)}finally{setLoading(false)}},[category,location]);
  const loadSeller=useCallback(async()=>{try{const r=await fetch('/api/marketplace/seller/plan'),d=await r.json().catch(()=>({}));if(r.ok)setSellerPlan(d.plan||null);if(!localStorage.getItem('myzubster-token'))return;const sr=await fetch('/api/marketplace/seller/me',{headers:authHeaders()}),sd=await sr.json().catch(()=>({}));if(sr.ok){setSellerState(sd);if(sd.active)trackConversionOnce('seller_subscription_success',{source:'seller_state'})}}catch(_){}},[]);
  useEffect(()=>{trackConversionOnce('marketplace_view',{path:'/marketplace'});trackConversionOnce('seller_offer_view',{source:sellerSource||'direct',fromZorgax});if(params.get('seller')==='success'){setMessage(t.success);trackConversionOnce('seller_checkout_return_success',{source:sellerSource||'direct'})}else if(params.get('seller')==='cancelled'){setMessage(t.cancelled);trackConversionOnce('seller_checkout_return_cancelled',{source:sellerSource||'direct'})}load();loadSeller()},[load,loadSeller,fromZorgax,params,sellerSource,t.cancelled,t.success]);
  useEffect(()=>{if(!demoDeepLink)return;const id=window.requestAnimationFrame(()=>{const el=demoSectionRef.current;if(!el)return;el.scrollIntoView({behavior:'smooth',block:'start'});el.focus({preventScroll:true});trackConversionOnce('marketplace_demo_deeplink_view',{source:sellerSource||'direct'})});return()=>window.cancelAnimationFrame(id)},[demoDeepLink,sellerSource]);
  useEffect(()=>{if(!selectedDemo)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';const id=window.requestAnimationFrame(()=>demoDialogRef.current?.focus());const onKeyDown=e=>{if(e.key==='Escape')closeDemo()};window.addEventListener('keydown',onKeyDown);return()=>{window.cancelAnimationFrame(id);window.removeEventListener('keydown',onKeyDown);document.body.style.overflow=previous}},[selectedDemo]);

  async function apiAction(url,body){const r=await fetch(url,{method:'POST',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||d.error||'Operation failed');e.status=r.status;throw e}return d}
  async function becomeSeller(){trackConversion('seller_cta_clicked',{source:sellerSource||'direct',fromZorgax});const returnTo=`${window.location.pathname}${window.location.search}${window.location.hash}`;if(!localStorage.getItem('myzubster-token')){setMessage(t.login);window.location.assign(`/social-login?returnTo=${encodeURIComponent(returnTo)}`);return}try{setMessage(t.checkout);trackConversion('seller_checkout_started',{source:sellerSource||'direct',fromZorgax});const payload=await apiAction('/api/marketplace/seller/checkout',{});if(!payload.checkoutUrl)throw new Error('Stripe Checkout unavailable');window.location.assign(payload.checkoutUrl)}catch(e){trackConversion('seller_checkout_error',{source:sellerSource||'direct',message:e.message});if(e.status===401){localStorage.removeItem('myzubster-token');window.location.assign(`/social-login?returnTo=${encodeURIComponent(returnTo)}`);return}setMessage(e.message)}}
  async function createListing(e){e.preventDefault();try{await apiAction('/api/listings/create',{...form,price:['FREE','BARTER'].includes(form.currency)?0:Number(form.price)});setMessage(t.published);setShowCreate(false);await load()}catch(e){setMessage(e.message)}}
  async function requestListing(l){try{await apiAction('/api/marketplace/orders',{listingId:l.id||l._id,quantity:1,note:''});setMessage('✓')}catch(e){setMessage(e.message)}}
  function openDemo(demo){setSelectedDemo(demo);setDemoFlow('idle');trackConversion('marketplace_demo_opened',{demoId:demo.id,category:demo.category})}
  function closeDemo(){setSelectedDemo(null);setDemoFlow('idle')}
  function startDemoRequest(){setDemoFlow('review');trackConversion('marketplace_demo_request_started',{demoId:selectedDemo?.id})}
  function confirmDemoRequest(){setDemoFlow('confirmed');trackConversion('marketplace_demo_request_confirmed',{demoId:selectedDemo?.id})}

  const displayPrice=sellerPlan?`${sellerPlan.amount} ${sellerPlan.currency}/month`:'9,90 EUR/month';
  const sellerTrialDays=Number(sellerPlan?.trialDays||0),sellerCta=sellerTrialDays>0?t.activateTrial.replace('{days}',sellerTrialDays):t.activate,sellerTerms=sellerTrialDays>0?t.trialTerms.replace('{days}',sellerTrialDays):t.cancel;
  const cardStyle={border:'1px dashed #2f9e66',padding:16,borderRadius:16,display:'flex',flexDirection:'column',gap:8,minWidth:0};
  return <main style={{padding:'clamp(14px,3vw,24px)',maxWidth:1100,margin:'0 auto'}}>
    <header><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div>MYZUBSTER MARKETPLACE</div><select value={lang} onChange={e=>setLangState(setLanguage(e.target.value))}>{Object.entries(LANGUAGE_NAMES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><h2>{t.title}</h2><p>{t.intro}</p>{fromZorgax&&<p style={{padding:12,border:'1px solid #5b5bd6',borderRadius:12}}><strong>🤖 Zorgax → Marketplace</strong><br/>{t.fromZorgax}</p>}
      {!sellerState?.active?<section style={{margin:'18px 0',padding:'clamp(14px,3vw,20px)',border:'1px solid #555',borderRadius:16}}><small>MYZUBSTER SELLER · {displayPrice}</small><h3>{t.seller}</h3><p style={{padding:12,border:'1px solid #2f9e66',borderRadius:12}}><strong>{t.cohort}</strong><br/>{t.cohortText}</p><h4>{t.why}</h4><ul>{t.benefits.map(x=><li key={x}>{x}</li>)}</ul><p>{t.buyer}</p><button onClick={becomeSeller}>{sellerCta}</button><p style={{fontSize:13,opacity:.75}}>{sellerTerms}</p></section>:<p><strong>✓ {t.active}.</strong></p>}
      <button onClick={()=>setShowCreate(v=>!v)}>{showCreate?t.close:t.publish}</button></header>
    {showCreate&&<form onSubmit={createListing} style={{display:'grid',gap:10,margin:'20px 0'}}><input required placeholder={t.formTitle} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select><textarea placeholder={t.desc} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder={t.place} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{currencies.map(c=><option key={c}>{c}</option>)}</select>{!['FREE','BARTER'].includes(form.currency)&&<input type="number" placeholder={t.price} value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/>}<button>{t.send}</button></form>}
    {message&&<p role="status">{message}</p>}
    <section style={{display:'flex',gap:10,flexWrap:'wrap'}}><select style={{flex:'1 1 190px'}} value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t.all}</option>{demoCategories.map(c=><option key={c}>{c}</option>)}</select><input style={{flex:'1 1 190px',minWidth:0}} placeholder={t.filter} value={location} onChange={e=>setLocation(e.target.value)}/><button onClick={load}>{t.refresh}</button></section>

    <section ref={demoSectionRef} tabIndex="-1" aria-labelledby="demo-sellers-title" style={{margin:'28px 0',padding:'clamp(14px,3vw,20px)',border:'1px solid #2f9e66',borderRadius:18,scrollMarginTop:20}}><h3 id="demo-sellers-title">{t.demoTitle}</h3><p>{t.demoNote}</p><p style={{padding:10,border:'1px solid #b45309',borderRadius:10}}><strong>{t.demoWarning}</strong></p>
      <div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center',marginBottom:16}}><input style={{flex:'1 1 210px',minWidth:0}} aria-label={t.demoSearch} placeholder={t.demoSearch} value={demoQuery} onChange={e=>setDemoQuery(e.target.value)}/><select style={{flex:'1 1 190px'}} aria-label={t.demoPayment} value={demoPayment} onChange={e=>setDemoPayment(e.target.value)}><option value="">{t.demoAllPayments}</option><option value="FREE">FREE</option><option value="BARTER">BARTER</option><option value="EUR">EUR</option><option value="MYZ">MYZ</option></select><span aria-live="polite">{filteredDemos.length}/{DEMO_SELLERS.length}</span></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(240px,100%),1fr))',gap:16}}>{filteredDemos.map(s=><article key={s.id} style={cardStyle}><div aria-hidden="true" style={{fontSize:42,minHeight:70,display:'grid',placeItems:'center',borderRadius:12,background:'linear-gradient(135deg,rgba(47,158,102,.14),rgba(91,91,214,.14))'}}>{s.icon}</div><small style={{fontWeight:700,color:'#2f9e66'}}>{t.demoBadge} · {s.category}</small><h3 style={{margin:'4px 0'}}>{s.name}</h3><p style={{margin:0}}>{s.location}</p><p><strong>{t.demoOffer}:</strong> {s.offer}</p><p><strong>{s.price}</strong> · {s.requests} {t.demoRequests}</p><p><strong>{t.demoAvailability}:</strong> {s.availability}</p><button onClick={()=>openDemo(s)}>{t.demoDetails}</button></article>)}</div>
      {!filteredDemos.length&&<p>{t.noDemoMatches}</p>}
    </section>

    {selectedDemo&&<div role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)closeDemo()}} style={{position:'fixed',inset:0,zIndex:1000,display:'grid',placeItems:'center',padding:12,background:'rgba(0,0,0,.68)'}}><section ref={demoDialogRef} tabIndex="-1" role="dialog" aria-modal="true" aria-labelledby="demo-detail-title" aria-describedby="demo-detail-description" style={{width:'min(720px,calc(100vw - 24px))',maxHeight:'calc(100vh - 24px)',overflowY:'auto',padding:'clamp(16px,4vw,24px)',border:'2px solid #5b5bd6',borderRadius:18,background:'Canvas',color:'CanvasText',boxSizing:'border-box',boxShadow:'0 18px 60px rgba(0,0,0,.35)'}}><div style={{position:'sticky',top:-1,zIndex:1,display:'flex',justifyContent:'flex-end',background:'Canvas',paddingBottom:8}}><button onClick={closeDemo} aria-label={t.closeDemo}>✕ {t.close}</button></div><div style={{fontSize:58}} aria-hidden="true">{selectedDemo.icon}</div><small>{t.demoBadge} · {selectedDemo.category}</small><h2 id="demo-detail-title">{selectedDemo.name}</h2>{DEMO_IMAGES[selectedDemo.id]&&<img src={DEMO_IMAGES[selectedDemo.id]} alt={selectedDemo.offer} loading="lazy" decoding="async" style={{display:'block',width:'100%',maxHeight:'420px',objectFit:'cover',borderRadius:14,margin:'10px 0 16px'}}/>}<p id="demo-detail-description">{selectedDemo.description}</p><p><strong>{selectedDemo.offer}</strong></p><p>{selectedDemo.location} · {selectedDemo.price} · {selectedDemo.availability}</p><dl>{selectedDemo.details.map(([label,value])=><div key={label} style={{display:'grid',gridTemplateColumns:'minmax(90px,140px) minmax(0,1fr)',gap:10,padding:'6px 0'}}><dt><strong>{label}</strong></dt><dd style={{margin:0,overflowWrap:'anywhere'}}>{value}</dd></div>)}</dl><p style={{padding:10,border:'1px solid #b45309',borderRadius:10}}><strong>{t.demoWarning}</strong></p>{demoFlow==='idle'&&<button onClick={startDemoRequest}>{t.demoRequest}</button>}{demoFlow==='review'&&<div><h3>{t.demoReview}</h3><p>{selectedDemo.offer} · {selectedDemo.price}</p><p>{t.demoLocalReview}</p><button onClick={confirmDemoRequest}>{t.demoConfirm}</button></div>}{demoFlow==='confirmed'&&<p role="status" style={{padding:12,border:'1px solid #2f9e66',borderRadius:10}}><strong>✓ {t.demoConfirmed}</strong></p>}<div style={{marginTop:18}}><button onClick={closeDemo}>← {t.demoBack}</button></div></section></div>}

    {loading&&<p>{t.loading}</p>}{error&&<p>{error}</p>}{!loading&&!error&&!listings.length&&<section><h3>{t.empty}</h3><p>{t.first}</p></section>}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(min(240px,100%),1fr))',gap:16}}>{listings.map(l=><article key={l.id||l._id} style={{border:'1px solid #555',padding:16,minWidth:0}}><small>{l.category}</small><h3>{l.title}</h3>{l.description&&<p>{l.description}</p>}<strong>{l.currency==='FREE'?t.free:l.currency==='BARTER'?t.barter:`${l.price} ${l.currency}`}</strong><div><button onClick={()=>requestListing(l)}>{t.request}</button></div></article>)}</section>
    <details style={{marginTop:28,padding:16,border:'1px solid #444',borderRadius:12}}><summary style={{cursor:'pointer'}}>{t.wallet}</summary><WalletHubPanel compact/></details>
    {!sellerState?.active&&<section style={{marginTop:28,padding:20,borderTop:'1px solid #444',textAlign:'center'}}><h3>{t.seller}</h3><p>{t.buyer}</p><button onClick={becomeSeller}>{sellerCta}</button></section>}
  </main>
}
export{categories as MARKETPLACE_CATEGORIES,DEMO_SELLERS,C as MARKETPLACE_COPY,demoPaymentMode,filterDemoSellers,isDemoDeepLink};
export default MarketplacePage;