import React,{useCallback,useEffect,useMemo,useState}from'react';
import WalletHubPanel from'../components/WalletHubPanel';
import{trackConversion,trackConversionOnce}from'../analytics/conversionAnalytics';
import{getLanguage,LANGUAGE_NAMES,setLanguage}from'../i18n';

const categories=['seeds','plants','produce','clothing','accessories','event_equipment','tools','services','volunteering','pet_adoption','pet_lost_found','pet_services'];
const currencies=['FREE','BARTER','MYZ','ETH','BTC','XMR','TARI'];
const DEMO_SELLERS=[
  {id:'demo-kefir',icon:'🥛',name:'Kefir Lab Demo',category:'produce',location:'Emilia-Romagna',offer:'Grani di kefir e guida introduttiva',description:'Esempio di scambio locale con istruzioni di conservazione e ritiro concordato.',price:'BARTER',requests:4,availability:'Su appuntamento',details:[['Tipo','Scambio alimentare'],['Consegna','Ritiro locale']]},
  {id:'demo-repair',icon:'🧰',name:'Circular Repair Demo',category:'services',location:'Cesena',offer:'Riparazione collaborativa di piccoli oggetti',description:'Sessione dimostrativa di diagnosi e riparazione con approccio circolare.',price:'15 MYZ',requests:7,availability:'Sabato',details:[['Durata','60 minuti'],['Modalità','In presenza']]},
  {id:'demo-seeds',icon:'🌾',name:'Seed Commons Demo',category:'seeds',location:'Italia',offer:'Scambio di semi locali tracciabili',description:'Lotto dimostrativo con provenienza e stagione consigliata.',price:'FREE',requests:3,availability:'Primavera',details:[['Provenienza','Locale'],['Scambio','Community']]},
  {id:'demo-sound-system',icon:'🔊',name:'Sound System Collective Demo',category:'tools',location:'Italia',offer:'Vendita o noleggio di un sound system artigianale completo',description:'Configurazione dimostrativa per eventi autorizzati, con trasporto da concordare.',price:'1.200 EUR',requests:9,availability:'Weekend',details:[['Potenza','Demo 6 kW'],['Uso','Eventi autorizzati']]},
  {id:'demo-audio-gear',icon:'🎚️',name:'Underground Audio Gear Demo',category:'tools',location:'Bologna',offer:'Mixer, amplificatori, cavi e componenti audio usati',description:'Set dimostrativo di attrezzatura usata verificabile prima dello scambio.',price:'BARTER',requests:6,availability:'Disponibile',details:[['Condizione','Usato'],['Scambio','Baratto']]},
  {id:'demo-event-tech',icon:'💡',name:'Free Party Tech Demo',category:'services',location:'Europa',offer:'Montaggio audio, luci e assistenza tecnica per eventi culturali',description:'Servizio demo per eventi legali e autorizzati, dalla preparazione al disallestimento.',price:'180 EUR',requests:5,availability:'Su calendario',details:[['Servizio','Audio + luci'],['Sicurezza','Evento autorizzato']]},
  {id:'demo-subculture-wear',icon:'🧥',name:'Subculture Wear Demo',category:'clothing',location:'Europa',offer:'Indumenti, patch, borse e accessori legati alle culture underground',description:'Capsule demo di abbigliamento recuperato e personalizzato.',price:'35 EUR',requests:8,availability:'Disponibile',details:[['Produzione','Upcycling'],['Taglia','Variabile']]},
  {id:'demo-event-sound-rental',icon:'🎛️',name:'Mobile Sound Rental Demo',category:'event_equipment',location:'Italia',offer:'Noleggio impianto audio completo per eventi con trasporto e montaggio',description:'Pacchetto dimostrativo con consegna, setup e ritiro.',price:'350 EUR',requests:11,availability:'Weekend',details:[['Include','Trasporto + setup'],['Uso','Eventi autorizzati']]},
  {id:'demo-dj-package',icon:'🎧',name:'DJ & Crew Demo',category:'services',location:'Italia',offer:'DJ set, selezione musicale e supporto tecnico per eventi',description:'Crew dimostrativa per programmazione musicale e supporto tecnico.',price:'220 EUR',requests:7,availability:'Su calendario',details:[['Durata','4 ore demo'],['Formato','DJ + supporto']]},
  {id:'demo-event-machines',icon:'🌫️',name:'Event Machines Demo',category:'event_equipment',location:'Emilia-Romagna',offer:'Noleggio luci, macchina del fumo, proiettori, generatori e attrezzature per eventi',description:'Catalogo dimostrativo di attrezzature per produzioni autorizzate.',price:'BARTER',requests:6,availability:'Disponibile',details:[['Inventario','Luci + effetti'],['Scambio','Baratto']]},
  {id:'demo-plants',icon:'🪴',name:'Community Plant Nursery Demo',category:'plants',location:'Italia',offer:'Piante locali con scheda di cura e provenienza documentata',description:'Pianta dimostrativa accompagnata da indicazioni di cura e provenienza.',price:'FREE',requests:3,availability:'Disponibile',details:[['Specie','Pianta locale demo'],['Cura','Scheda inclusa']]},
  {id:'demo-accessories',icon:'🎒',name:'Upcycled Accessories Demo',category:'accessories',location:'Europa',offer:'Borse, patch e accessori realizzati con materiali recuperati',description:'Accessori demo realizzati da materiali riutilizzati.',price:'20 MYZ',requests:5,availability:'Disponibile',details:[['Materiale','Recuperato'],['Produzione','Artigianale']]},
  {id:'demo-volunteering',icon:'🤝',name:'Community Garden Volunteers Demo',category:'volunteering',location:'Emilia-Romagna',offer:'Supporto volontario per cura degli orti e documentazione delle attività',description:'Turno demo di volontariato: nessun pagamento, solo disponibilità e coordinamento.',price:'FREE',requests:4,availability:'Sabato mattina',details:[['Impegno','2 ore'],['Attività','Cura orto e documentazione'],['Compenso','Nessuno · volontariato']]},
  {id:'demo-pet-adoption',icon:'🐶',name:'Responsible Pet Adoption Demo',category:'pet_adoption',location:'Italia',offer:'Profilo dimostrativo per adozione responsabile tramite associazione verificata',description:'Esempio di scheda adozione con contatto mediato da associazione. Nessun acquisto di animali.',price:'FREE',requests:6,availability:'Colloquio richiesto',details:[['Animale','Cane adulto demo'],['Età','4 anni'],['Referente','Associazione demo'],['Procedura','Colloquio + verifica adozione']]},
  {id:'demo-pet-lost-found',icon:'🔎',name:'Lost & Found Pet Alert Demo',category:'pet_lost_found',location:'Italia',offer:'Segnalazione dimostrativa con zona approssimativa e contatto autorizzato',description:'Segnalazione demo progettata per proteggere dati sensibili e posizione esatta.',price:'FREE',requests:2,availability:'Segnalazione aperta',details:[['Stato','Trovato'],['Area','Zona approssimativa'],['Privacy','Posizione esatta non pubblicata']]},
  {id:'demo-pet-services',icon:'🐾',name:'Local Pet Care Demo',category:'pet_services',location:'Cesena',offer:'Passeggiate e assistenza quotidiana per animali domestici',description:'Servizio demo di pet care con disponibilità e area di copertura.',price:'12 EUR',requests:5,availability:'Lun–Ven',details:[['Servizio','Passeggiata 45 min'],['Copertura','Cesena'],['Animali','Cani e gatti']]}
];

function demoPaymentMode(price=''){if(price==='FREE')return'FREE';if(price==='BARTER')return'BARTER';if(/MYZ/i.test(price))return'MYZ';if(/EUR|€/i.test(price))return'EUR';return'OTHER'}
function filterDemoSellers(rows,{category='',location='',query='',payment=''}){const q=query.trim().toLowerCase(),place=location.trim().toLowerCase();return rows.filter(row=>(!category||row.category===category)&&(!place||row.location.toLowerCase().includes(place))&&(!payment||demoPaymentMode(row.price)===payment)&&(!q||[row.name,row.offer,row.description,row.category,row.location].some(v=>String(v||'').toLowerCase().includes(q))))}

const BASE_COPY={title:'Publish your offer and receive real requests',intro:'Create a Seller space for products, services or projects. Browsing stays free.',seller:'Open your MyZubster Seller space',activate:'Become a Seller · €9.90/month',active:'Seller active',publish:'Publish listing',close:'Close',desc:'Description',place:'Location',price:'Price',send:'Publish',all:'All categories',filter:'Filter location',refresh:'Refresh',loading:'Loading listings…',empty:'No public listings yet',first:'You can be the first to publish one.',request:'Request',free:'Free',barter:'Barter',login:'Sign in before becoming a Seller.',checkout:'Opening Stripe Checkout…',published:'Listing published.',why:'What you get',benefits:['Publish products, services and projects','Manage listings and availability','Receive requests from the community','Build reputation from completed exchanges'],buyer:'Buying and discovering stays free.',cancel:'Monthly subscription. Cancel from your account.',fromZorgax:'Zorgax brought you here: turn your idea into a real Seller space.',success:'Payment received. We are verifying and activating your Seller profile.',activateTrial:'Start {days} days free',trialTerms:'Eligible new Sellers are not charged for {days} days; then €9.90/month.',cohort:'Founding Seller cohort',cohortText:'We are forming the first group of real offers and measuring verifiable requests. No sales are promised.',wallet:'Wallets and digital payments',demoTitle:'Marketplace Demo v2',demoNote:'Interactive demonstration profiles. No demo can create a real order or payment.',demoBadge:'DEMO',demoOffer:'Example offer',demoRequests:'simulated requests',demoTry:'Create your real Seller',demoSearch:'Search demos',demoPayment:'Demo payment type',demoAllPayments:'All demo modes',demoDetails:'Open demo',demoAvailability:'Availability',demoRequest:'Try request flow',demoWarning:'DEMO ONLY — no order, payment, message or personal data is created.',demoReview:'Review simulated request',demoConfirm:'Confirm simulated request',demoConfirmed:'Demo request confirmed locally. Nothing was sent and no payment was created.',demoBack:'Back to demos'};
const C={
  en:BASE_COPY,
  it:{...BASE_COPY,title:'Pubblica la tua offerta e ricevi richieste reali',intro:'Crea uno spazio Seller per prodotti, servizi o progetti. Il Marketplace resta gratuito per chi cerca e acquista.',seller:'Apri il tuo spazio Seller MyZubster',activate:'Diventa Seller · 9,90 €/mese',active:'Seller attivo',publish:'Pubblica annuncio',close:'Chiudi',desc:'Descrizione',place:'Località',price:'Prezzo',send:'Pubblica',all:'Tutte le categorie',filter:'Filtra località',refresh:'Aggiorna',loading:'Caricamento annunci…',empty:'Nessun annuncio pubblico per ora',first:'Puoi essere il primo a pubblicarne uno.',request:'Richiedi',free:'Gratis',barter:'Baratto',login:'Per diventare Seller devi prima accedere a MyZubster.',checkout:'Apertura Stripe Checkout…',published:'Annuncio pubblicato.',why:'Cosa ottieni',buyer:'Per chi compra e scopre il Marketplace resta gratuito.',cancel:'Abbonamento mensile. Puoi annullare dal tuo account.',fromZorgax:'Zorgax ti ha portato qui: ora puoi trasformare la tua idea in uno spazio Seller reale.',success:'Pagamento ricevuto. Stiamo verificando e attivando il tuo profilo Seller.',activateTrial:'Inizia {days} giorni gratis',trialTerms:'Per i nuovi Seller idonei: nessun addebito per {days} giorni, poi 9,90 €/mese.',cohort:'Cohort Founding Seller',cohortText:'Stiamo formando il primo gruppo di offerte reali e raccogliendo richieste verificabili. Nessuna promessa di vendite.',wallet:'Wallet e pagamenti digitali',demoTitle:'Marketplace Demo v2',demoNote:'Profili dimostrativi interattivi. Nessuna demo può creare ordini o pagamenti reali.',demoOffer:'Offerta di esempio',demoRequests:'richieste simulate',demoTry:'Crea il tuo Seller reale',demoSearch:'Cerca nelle demo',demoPayment:'Tipo pagamento demo',demoAllPayments:'Tutte le modalità demo',demoDetails:'Apri demo',demoAvailability:'Disponibilità',demoRequest:'Prova flusso richiesta',demoWarning:'SOLO DEMO — non viene creato alcun ordine, pagamento, messaggio o dato personale.',demoReview:'Rivedi richiesta simulata',demoConfirm:'Conferma richiesta simulata',demoConfirmed:'Richiesta demo confermata solo localmente. Non è stato inviato nulla e non è stato creato alcun pagamento.',demoBack:'Torna alle demo'},
  es:{...BASE_COPY,demoTitle:'Marketplace Demo v2',demoNote:'Perfiles interactivos de demostración. No crean pedidos ni pagos reales.'},
  fr:{...BASE_COPY,demoTitle:'Marketplace Demo v2',demoNote:'Profils de démonstration interactifs. Aucun achat ni paiement réel.'},
  de:{...BASE_COPY,demoTitle:'Marketplace Demo v2',demoNote:'Interaktive Demoprofile. Keine echten Bestellungen oder Zahlungen.'}
};

function authHeaders(extra={}){const token=localStorage.getItem('myzubster-token');return{...extra,...(token?{Authorization:`Bearer ${token}`}:{})}}

function MarketplacePage(){
  const[lang,setLangState]=useState(getLanguage),t=C[lang]||C.en,[listings,setListings]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[category,setCategory]=useState(''),[location,setLocation]=useState(''),[showCreate,setShowCreate]=useState(false),[form,setForm]=useState({title:'',category:'services',description:'',location:'',price:'',currency:'FREE'}),[message,setMessage]=useState(''),[sellerPlan,setSellerPlan]=useState(null),[sellerState,setSellerState]=useState(null),[demoQuery,setDemoQuery]=useState(''),[demoPayment,setDemoPayment]=useState(''),[selectedDemo,setSelectedDemo]=useState(null),[demoFlow,setDemoFlow]=useState('idle');
  const params=useMemo(()=>new URLSearchParams(window.location.search),[]);
  const sellerSource=params.get('from')||params.get('utm_source')||'';
  const fromZorgax=sellerSource.toLowerCase().includes('zorgax')||params.get('intent')==='seller';
  const filteredDemos=useMemo(()=>filterDemoSellers(DEMO_SELLERS,{category,location,query:demoQuery,payment:demoPayment}),[category,location,demoQuery,demoPayment]);

  const load=useCallback(async()=>{setLoading(true);setError('');try{const p=new URLSearchParams();if(category)p.set('category',category);if(location)p.set('location',location);const r=await fetch(`/api/listings?${p}`),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||'Marketplace unavailable');setListings(Array.isArray(d.listings)?d.listings:[])}catch(e){setError(e.message)}finally{setLoading(false)}},[category,location]);
  const loadSeller=useCallback(async()=>{try{const r=await fetch('/api/marketplace/seller/plan'),d=await r.json().catch(()=>({}));if(r.ok)setSellerPlan(d.plan||null);if(!localStorage.getItem('myzubster-token'))return;const sr=await fetch('/api/marketplace/seller/me',{headers:authHeaders()}),sd=await sr.json().catch(()=>({}));if(sr.ok){setSellerState(sd);if(sd.active)trackConversionOnce('seller_subscription_success',{source:'seller_state'})}}catch(_){}},[]);
  useEffect(()=>{trackConversionOnce('marketplace_view',{path:'/marketplace'});trackConversionOnce('seller_offer_view',{source:sellerSource||'direct',fromZorgax});if(params.get('seller')==='success'){setMessage(t.success);trackConversionOnce('seller_checkout_return_success',{source:sellerSource||'direct'})}load();loadSeller()},[load,loadSeller,fromZorgax,params,sellerSource,t.success]);

  async function apiAction(url,body){const r=await fetch(url,{method:'POST',headers:authHeaders({'Content-Type':'application/json'}),body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.message||d.error||'Operation failed');e.status=r.status;throw e}return d}
  async function becomeSeller(){trackConversion('seller_cta_clicked',{source:sellerSource||'direct',fromZorgax});const returnTo=`${window.location.pathname}${window.location.search}${window.location.hash}`;if(!localStorage.getItem('myzubster-token')){setMessage(t.login);window.location.assign(`/social-login?returnTo=${encodeURIComponent(returnTo)}`);return}try{setMessage(t.checkout);trackConversion('seller_checkout_started',{source:sellerSource||'direct',fromZorgax});const payload=await apiAction('/api/marketplace/seller/checkout',{});if(!payload.checkoutUrl)throw new Error('Stripe Checkout unavailable');window.location.assign(payload.checkoutUrl)}catch(e){trackConversion('seller_checkout_error',{source:sellerSource||'direct',message:e.message});if(e.status===401){localStorage.removeItem('myzubster-token');window.location.assign(`/social-login?returnTo=${encodeURIComponent(returnTo)}`);return}setMessage(e.message)}}
  async function createListing(e){e.preventDefault();try{await apiAction('/api/listings/create',{...form,price:['FREE','BARTER'].includes(form.currency)?0:Number(form.price)});setMessage(t.published);setShowCreate(false);await load()}catch(e){setMessage(e.message)}}
  async function requestListing(l){try{await apiAction('/api/marketplace/orders',{listingId:l.id||l._id,quantity:1,note:''});setMessage('✓')}catch(e){setMessage(e.message)}}
  function openDemo(demo){setSelectedDemo(demo);setDemoFlow('idle');trackConversion('marketplace_demo_opened',{demoId:demo.id,category:demo.category})}
  function closeDemo(){setSelectedDemo(null);setDemoFlow('idle')}
  function startDemoRequest(){setDemoFlow('review');trackConversion('marketplace_demo_request_started',{demoId:selectedDemo?.id})}
  function confirmDemoRequest(){setDemoFlow('confirmed');trackConversion('marketplace_demo_request_confirmed',{demoId:selectedDemo?.id})}

  const displayPrice=sellerPlan?`${sellerPlan.amount} ${sellerPlan.currency}/month`:'9,90 EUR/month';
  const sellerTrialDays=Number(sellerPlan?.trialDays||0),sellerCta=sellerTrialDays>0?t.activateTrial.replace('{days}',sellerTrialDays):t.activate,sellerTerms=sellerTrialDays>0?t.trialTerms.replace('{days}',sellerTrialDays):t.cancel;
  const cardStyle={border:'1px dashed #2f9e66',padding:16,borderRadius:16,display:'flex',flexDirection:'column',gap:8};
  return <main style={{padding:24,maxWidth:1100,margin:'0 auto'}}>
    <header><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div>MYZUBSTER MARKETPLACE</div><select value={lang} onChange={e=>setLangState(setLanguage(e.target.value))}>{Object.entries(LANGUAGE_NAMES).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><h2>{t.title}</h2><p>{t.intro}</p>{fromZorgax&&<p style={{padding:12,border:'1px solid #5b5bd6',borderRadius:12}}><strong>🤖 Zorgax → Marketplace</strong><br/>{t.fromZorgax}</p>}
      {!sellerState?.active?<section style={{margin:'18px 0',padding:20,border:'1px solid #555',borderRadius:16}}><small>MYZUBSTER SELLER · {displayPrice}</small><h3>{t.seller}</h3><p style={{padding:12,border:'1px solid #2f9e66',borderRadius:12}}><strong>{t.cohort}</strong><br/>{t.cohortText}</p><h4>{t.why}</h4><ul>{t.benefits.map(x=><li key={x}>{x}</li>)}</ul><p>{t.buyer}</p><button onClick={becomeSeller}>{sellerCta}</button><p style={{fontSize:13,opacity:.75}}>{sellerTerms}</p></section>:<p><strong>✓ {t.active}.</strong></p>}
      <button onClick={()=>setShowCreate(v=>!v)}>{showCreate?t.close:t.publish}</button></header>
    {showCreate&&<form onSubmit={createListing} style={{display:'grid',gap:10,margin:20}}><input required placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select><textarea placeholder={t.desc} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input placeholder={t.place} value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{currencies.map(c=><option key={c}>{c}</option>)}</select>{!['FREE','BARTER'].includes(form.currency)&&<input type="number" placeholder={t.price} value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/>}<button>{t.send}</button></form>}
    {message&&<p role="status">{message}</p>}
    <section style={{display:'flex',gap:10,flexWrap:'wrap'}}><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">{t.all}</option>{categories.map(c=><option key={c}>{c}</option>)}</select><input placeholder={t.filter} value={location} onChange={e=>setLocation(e.target.value)}/><button onClick={load}>{t.refresh}</button></section>

    <section aria-labelledby="demo-sellers-title" style={{margin:'28px 0',padding:20,border:'1px solid #2f9e66',borderRadius:18}}><h3 id="demo-sellers-title">{t.demoTitle}</h3><p>{t.demoNote}</p><p style={{padding:10,border:'1px solid #b45309',borderRadius:10}}><strong>{t.demoWarning}</strong></p>
      <div style={{display:'flex',gap:10,flexWrap:'wrap',marginBottom:16}}><input aria-label={t.demoSearch} placeholder={t.demoSearch} value={demoQuery} onChange={e=>setDemoQuery(e.target.value)}/><select aria-label={t.demoPayment} value={demoPayment} onChange={e=>setDemoPayment(e.target.value)}><option value="">{t.demoAllPayments}</option><option value="FREE">FREE</option><option value="BARTER">BARTER</option><option value="EUR">EUR</option><option value="MYZ">MYZ</option></select><span>{filteredDemos.length}/{DEMO_SELLERS.length}</span></div>
      <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:16}}>{filteredDemos.map(s=><article key={s.id} style={cardStyle}><div aria-hidden="true" style={{fontSize:42,minHeight:70,display:'grid',placeItems:'center',borderRadius:12,background:'linear-gradient(135deg,rgba(47,158,102,.14),rgba(91,91,214,.14))'}}>{s.icon}</div><small style={{fontWeight:700,color:'#2f9e66'}}>{t.demoBadge} · {s.category}</small><h3 style={{margin:'4px 0'}}>{s.name}</h3><p style={{margin:0}}>{s.location}</p><p><strong>{t.demoOffer}:</strong> {s.offer}</p><p><strong>{s.price}</strong> · {s.requests} {t.demoRequests}</p><p><strong>{t.demoAvailability}:</strong> {s.availability}</p><button onClick={()=>openDemo(s)}>{t.demoDetails}</button></article>)}</div>
      {!filteredDemos.length&&<p>Nessuna demo corrisponde ai filtri selezionati.</p>}
    </section>

    {selectedDemo&&<section role="dialog" aria-modal="true" aria-labelledby="demo-detail-title" style={{margin:'24px 0',padding:22,border:'2px solid #5b5bd6',borderRadius:18}}><button onClick={closeDemo}>← {t.demoBack}</button><div style={{fontSize:58,marginTop:12}} aria-hidden="true">{selectedDemo.icon}</div><small>{t.demoBadge} · {selectedDemo.category}</small><h2 id="demo-detail-title">{selectedDemo.name}</h2><p>{selectedDemo.description}</p><p><strong>{selectedDemo.offer}</strong></p><p>{selectedDemo.location} · {selectedDemo.price} · {selectedDemo.availability}</p><dl>{selectedDemo.details.map(([label,value])=><div key={label} style={{display:'grid',gridTemplateColumns:'minmax(110px,.4fr) 1fr',gap:10,padding:'6px 0'}}><dt><strong>{label}</strong></dt><dd style={{margin:0}}>{value}</dd></div>)}</dl><p style={{padding:10,border:'1px solid #b45309',borderRadius:10}}><strong>{t.demoWarning}</strong></p>{demoFlow==='idle'&&<button onClick={startDemoRequest}>{t.demoRequest}</button>}{demoFlow==='review'&&<div><h3>{t.demoReview}</h3><p>{selectedDemo.offer} · {selectedDemo.price}</p><p>Questa conferma modifica solo lo stato della demo nel browser.</p><button onClick={confirmDemoRequest}>{t.demoConfirm}</button></div>}{demoFlow==='confirmed'&&<p role="status" style={{padding:12,border:'1px solid #2f9e66',borderRadius:10}}><strong>✓ {t.demoConfirmed}</strong></p>}</section>}

    {loading&&<p>{t.loading}</p>}{error&&<p>{error}</p>}{!loading&&!error&&!listings.length&&<section><h3>{t.empty}</h3><p>{t.first}</p></section>}
    <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:16}}>{listings.map(l=><article key={l.id||l._id} style={{border:'1px solid #555',padding:16}}><small>{l.category}</small><h3>{l.title}</h3>{l.description&&<p>{l.description}</p>}<strong>{l.currency==='FREE'?t.free:l.currency==='BARTER'?t.barter:`${l.price} ${l.currency}`}</strong><div><button onClick={()=>requestListing(l)}>{t.request}</button></div></article>)}</section>
    <details style={{marginTop:28,padding:16,border:'1px solid #444',borderRadius:12}}><summary style={{cursor:'pointer'}}>{t.wallet}</summary><WalletHubPanel compact/></details>
    {!sellerState?.active&&<section style={{marginTop:28,padding:20,borderTop:'1px solid #444',textAlign:'center'}}><h3>{t.seller}</h3><p>{t.buyer}</p><button onClick={becomeSeller}>{sellerCta}</button></section>}
  </main>
}
export{categories as MARKETPLACE_CATEGORIES,DEMO_SELLERS,demoPaymentMode,filterDemoSellers};
export default MarketplacePage;
