import React, { useState } from 'react';
import MapPage from './pages/MapPage';
import GardensPage from './pages/GardensPage';
import ClowbotBountiesPage from './pages/ClowbotBountiesPage';
import MetaversePage from './pages/MetaversePage';
import MarketplacePage from './pages/MarketplacePage';
import MarketplaceOpsPage from './pages/MarketplaceOpsPage';
import SocialLoginPage from './pages/SocialLoginPage';
import ZorgaxLifePilotPage from './pages/ZorgaxLifePilotPage';
import AppsDownloadPage from './pages/AppsDownloadPage';
import RobotPublicWalletPanel from './components/RobotPublicWalletPanel';
import { trackConversion } from './analytics/conversionAnalytics';

const TABS={WORLD:'world',EXPLORE:'explore',GARDENS:'gardens',MISSIONS:'missions',MARKETPLACE:'marketplace',MARKETPLACE_OPS:'marketplace-ops'};
const lifeSpotlightStyle={margin:'0 20px 20px',padding:'22px',borderRadius:'18px',border:'1px solid rgba(34,197,94,.35)',background:'linear-gradient(135deg,rgba(34,197,94,.12),rgba(168,85,247,.12))'};
const lifeActionsStyle={display:'flex',flexWrap:'wrap',gap:'10px',marginTop:'14px'};
const lifeLinkStyle={display:'inline-block',padding:'11px 15px',borderRadius:'10px',textDecoration:'none',fontWeight:900,color:'inherit',border:'1px solid currentColor'};
const introStyle={margin:'8px 20px 20px',padding:'26px',borderRadius:'20px',border:'1px solid rgba(168,85,247,.38)',background:'linear-gradient(135deg,rgba(168,85,247,.15),rgba(59,130,246,.12))'};
const marketplaceSpotlightStyle={margin:'0 20px 20px',padding:'22px',borderRadius:'18px',border:'1px solid rgba(59,130,246,.38)',background:'linear-gradient(135deg,rgba(59,130,246,.14),rgba(168,85,247,.12))'};
const zorgaxButtonStyle={position:'fixed',right:18,bottom:18,zIndex:1000,border:'1px solid rgba(168,85,247,.55)',borderRadius:999,padding:'12px 16px',fontWeight:900,cursor:'pointer',boxShadow:'0 8px 28px rgba(0,0,0,.25)'};
const zorgaxPanelStyle={position:'fixed',right:18,bottom:76,zIndex:1000,width:'min(390px,calc(100vw - 36px))',padding:18,borderRadius:18,border:'1px solid rgba(168,85,247,.55)',background:'rgba(20,20,30,.97)',color:'#fff',boxShadow:'0 16px 45px rgba(0,0,0,.38)'};
function trackLifeCta(destination){if(typeof window.va==='function')window.va('event',{name:'Homepage LIFE CTA',data:{destination}});}
function FirstVisitIntro(){return <section style={introStyle}><div style={{fontSize:13,fontWeight:900}}>COS'E MYZUBSTER?</div><h2 style={{margin:'6px 0 8px',fontSize:28}}>Un ecosistema open source dove persone, progetti e idee diventano collaborazione e valore.</h2><p>MyZubster riunisce un mondo digitale, missioni, progetti ambientali e un Marketplace. Puoi esplorare gratuitamente, partecipare alla comunita, contribuire a progetti e pubblicare prodotti o servizi come Seller.</p><div style={lifeActionsStyle}><a href="/come-funziona" style={lifeLinkStyle}>Capisci MyZubster in 1 minuto →</a><a href="/marketplace" style={lifeLinkStyle}>Esplora il Marketplace →</a><a href="/social-login" style={lifeLinkStyle}>Entra nella comunita →</a></div></section>}
function LifeSpotlight(){return <section style={lifeSpotlightStyle}><h2>🌍 Dati → evidenze → KPI/MRV → impatto replicabile</h2><p>MyZubster sta validando un percorso evidence-first per pilot ambientali, con focus su acqua, agricoltura, provenance dei dati e MRV digitale.</p><div style={lifeActionsStyle}><a href="/life-pilot" onClick={()=>trackLifeCta('life-pilot')} style={lifeLinkStyle}>Esplora LIFE Pilot →</a></div></section>}
function MarketplaceSpotlight(){return <section style={marketplaceSpotlightStyle}><h2>🛒 Trasforma ciò che sai fare in valore</h2><p>Esplora gratuitamente prodotti, servizi e proposte della comunità. Con MyZubster Seller puoi aprire il tuo spazio e pubblicare annunci.</p><div style={lifeActionsStyle}><a href="/marketplace" style={lifeLinkStyle}>Esplora il Marketplace →</a></div></section>}
function ZorgaxAssistant(){
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[messages,setMessages]=useState([{role:'assistant',content:'Ciao! Sono Zorgax 👽. Chiedimi qualsiasi cosa su MyZubster, Marketplace, Seller, Metaverso o LIFE.'}]);
 const send=async(e)=>{e.preventDefault();const text=input.trim();if(!text||busy)return;const userMessage={role:'user',content:text};const next=[...messages,userMessage];setMessages(next);setInput('');setBusy(true);trackConversion('zorgax_chat_message_sent',{source:'homepage_popup'});try{const history=messages.slice(-8).map(m=>({role:m.role,content:m.content}));const response=await fetch('/api/zorgax/assistant/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history,useWeb:false})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Risposta non disponibile');const reply=data.answer||data.response||data.message||'Ho ricevuto la domanda, ma non ho una risposta disponibile.';setMessages([...next,{role:'assistant',content:String(reply)}]);trackConversion('zorgax_chat_answer_received',{source:'homepage_popup'});}catch(error){setMessages([...next,{role:'assistant',content:'In questo momento non riesco a collegarmi al cervello di Zorgax. Puoi comunque esplorare MyZubster e riprovare tra poco.'}]);trackConversion('zorgax_chat_error',{source:'homepage_popup'});}finally{setBusy(false);}};
 return <><button type="button" aria-expanded={open} onClick={()=>{setOpen(!open);trackConversion(!open?'zorgax_assistant_opened':'zorgax_assistant_closed',{source:'floating_button'})}} style={zorgaxButtonStyle}>👽 {open?'Chiudi Zorgax':'Chatta con Zorgax'}</button>{open&&<aside role="dialog" aria-label="Chat con Zorgax" style={zorgaxPanelStyle}><div style={{fontSize:12,fontWeight:900,opacity:.75}}>ZORGAX · ASSISTENTE INTERATTIVO</div><h3 style={{margin:'6px 0 10px'}}>👽 Chiedimi qualcosa</h3><div aria-live="polite" style={{display:'grid',gap:8,maxHeight:280,overflowY:'auto',marginBottom:12}}>{messages.map((m,i)=><div key={i} style={{padding:'9px 11px',borderRadius:12,background:m.role==='user'?'rgba(59,130,246,.24)':'rgba(168,85,247,.18)',marginLeft:m.role==='user'?32:0,marginRight:m.role==='assistant'?32:0,lineHeight:1.4}}><strong>{m.role==='user'?'Tu':'Zorgax'}:</strong> {m.content}</div>)}{busy&&<div style={{opacity:.75}}>Zorgax sta pensando…</div>}</div><form onSubmit={send} style={{display:'flex',gap:8}}><input aria-label="Messaggio per Zorgax" value={input} onChange={e=>setInput(e.target.value)} maxLength={1000} placeholder="Scrivi una domanda…" style={{flex:1,minWidth:0,padding:11,borderRadius:10,border:'1px solid #666',fontSize:16}}/><button type="submit" disabled={busy||!input.trim()} style={{padding:'10px 14px',fontWeight:900}}>Invia</button></form><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><a href="/marketplace" style={{color:'#fff'}}>🛒 Marketplace</a><a href="/metaverse" style={{color:'#fff'}}>🪐 Metaverso</a><a href="/come-funziona" style={{color:'#fff'}}>🌍 Come funziona</a></div></aside>}</>;
}
function App(){const[activeTab,setActiveTab]=useState(TABS.WORLD);const path=window.location.pathname.replace(/\/+$/,'')||'/';if(path==='/social-login'||path==='/social-login.html')return <SocialLoginPage/>;if(path==='/life-pilot'||path==='/zorgax/life-pilot')return <ZorgaxLifePilotPage/>;if(path==='/apps')return <AppsDownloadPage/>;if(path==='/marketplace')return <MarketplacePage/>;if(path==='/metaverse')return <MetaversePage/>;return <div className="App"><nav style={{padding:'12px 20px',display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}><h1 style={{margin:0,fontSize:20}}>🌍 MyZubster</h1><a href="/social-login">🔐 Entra in MyZubster</a><a href="/marketplace">🛒 Scopri il Marketplace</a><button onClick={()=>setActiveTab(TABS.WORLD)}>Entra</button><button onClick={()=>setActiveTab(TABS.EXPLORE)}>Esplora</button><button onClick={()=>setActiveTab(TABS.GARDENS)}>Il mio giardino</button><button onClick={()=>setActiveTab(TABS.MISSIONS)}>Missioni</button><button onClick={()=>setActiveTab(TABS.MARKETPLACE)}>Marketplace</button><button onClick={()=>setActiveTab(TABS.MARKETPLACE_OPS)}>I miei scambi</button><a href="/zorgax">Zorgax</a><a href="/life-pilot">LIFE Pilot</a><a href="#robot-wallets">Robot XMR/BTC</a><a href="/press">Press</a><a href="/fumetto">Fumetto</a></nav><FirstVisitIntro/><MarketplaceSpotlight/><LifeSpotlight/><RobotPublicWalletPanel/>{activeTab===TABS.WORLD&&<MetaversePage/>}{activeTab===TABS.EXPLORE&&<MapPage/>}{activeTab===TABS.GARDENS&&<GardensPage/>}{activeTab===TABS.MISSIONS&&<ClowbotBountiesPage/>}{activeTab===TABS.MARKETPLACE&&<MarketplacePage/>}{activeTab===TABS.MARKETPLACE_OPS&&<MarketplaceOpsPage/>}<ZorgaxAssistant/></div>}
export default App;
